muxinc/media-chrome

- src/js/media-mute-button.js
- src/js/media-volume-range.js
Currently when the video/audio starts muted with volume zero, and then you click the _unmute_ button, nothing appears to change. It is actually toggling mute/unmute, but because the volume is still zero, the icon doesn't change.
This update bumps the volume to 0.25 when unmuting the volume is zero.
> Turn up volume if zero when unmuted

- ARCHITECTURE.md
- README.md
- examples/demo.html
- examples/hls.html
- examples/netflix-theme.html
- examples/youtube-theme.html
- examples/youtube.html
- index.html
- index.js
- src/js/media-container.js
In #10 we talked about changing the name of the main `<media-chrome>` element to disambiguate the class and element with the parent project. This PR changes it to `<media-container>` but aliases it to `<media-chrome>` so it's not an immediately breaking change.
More demos will need to be updated.
> Change main container name and deprecate media-chrome el

- src/js/utils/server-safe-globals.js
In some environments there are preexisting `window` shims that do not have the `customElements` on the window object. This update will check for those cases.
See: https://github.com/sanity-io/sanity-plugin-mux-input/issues/36#issuecomment-867955123
> Update 'isServer' to also check for customElements

- package.json
- src/js/media-mute-button.js
- src/js/media-pip-button.js
- src/js/media-play-button.js
- src/js/media-seek-backward-button.js
- src/js/media-seek-forward-button.js
- src/js/media-volume-range.js
**before**
```
❯ npx npm-packlist
LICENSE
dist/index.js
package.json
README.md
```
**after** - now the extras and individual elements will be included
```
❯ npx npm-packlist
LICENSE
dist/utils/defineCustomElement.js
dist/utils/fullscreenApi.js
dist/extras/media-clip-selector/index.js
dist/index.js
dist/media-chrome-button.js
dist/media-chrome-html-element.js
dist/media-chrome-range.js
dist/media-container.js
dist/media-control-bar.js
dist/media-controller.js
dist/media-current-time-display.js
dist/media-duration-display.js
dist/media-fullscreen-button.js
dist/media-mute-button.js
dist/media-pip-button.js
dist/media-play-button.js
dist/media-playback-rate-button.js
dist/media-poster.js
dist/media-progress-range.js
dist/media-seek-backward-button.js
dist/media-seek-forward-button.js …
```
> fix files that get published to npm, fix custom element constructor and fix some missing server safe globals

- README.md
- examples/basic.html
- examples/control-elements/media-time-display.html
- examples/index.html
- examples/themes/netflix-theme.html
- examples/themes/spotify-theme.html
- examples/themes/youtube-theme.html
- index.js
- package-lock.json
- src/js/media-chrome-button.js
- src/js/media-container.js
- src/js/media-control-bar.js
- src/js/media-current-time-display.js
- src/js/media-duration-display.js
- src/js/media-mute-button.js
- src/js/media-time-display.js
- src/js/utils/time.js
* Added an audio example to basic.html
* Added a spotify-like theme (more work needed to finish it, but it works)
* Added a `<media-time-display>` element to make it easy to show the current time and duration. Can probably replace media-current-time-display.
* Separated out video-specific styles in media-controller to allow audio players to be display: inline-flex and not have default height and widths like a video. This might not be the best approach but today you would add an `audio` attribute to media-controller to signal the audio-friendly layout.
* Removed the `#container` from the shadow dom of media-controller. This made it so you couldn't change the media-controller flex box settings, because they were all in the shadow dom instead of :host. 
* Made the `formatTime` function …
> Basic audio player styling and examples

- src/js/media-controller.js
Fix `media.textTracks` being undefined and trying to access `media.textTracks.addEventListener` or  `media.textTracks.removeEventListener`.
> Fix `.textTracks` undefined error

- src/js/media-controller.js
Fixes #110 Closes #55
If element fullscreen APIs don't exist, the media controller will now try APIs on the media element itself.
> Fix ios fullscreen

- docs/media-loading-indicator.md
- docs/styling.md
- examples/control-elements/media-loading-indicator.html
- examples/index.html
This change adds an example and the docs for the `<media-loading-indicator>` element.
The code is already merged to main:
https://github.com/muxinc/media-chrome/commit/abc07f6a198c1fc7d630caf8ed0c63dcc7872c3b
> Add loading indicator example and docs

- src/js/media-controller.js
From @heff's comment https://github.com/muxinc/media-chrome/pull/127#discussion_r792955048
> Remove stalled event for loading indicator

- src/js/media-container.js
This change only adds the opacity and transition CSS if the element does not have `no-auto-hide`.
This fixes an issue where these non auto hiding elements want to set opacity or transition themselves and it would get overwritten by the CSS in media-container.
Also removed `visibility: visible` in this change as it's unneeded I believe. it's the default.
> Add more selective css to prevent overwrites

- src/js/media-controller.js
- src/js/utils/element-utils.js
This change adds some fixes for PiP and fullscreen when media-chrome itself is part of a shadow DOM.
`this.getRootNode();` would then point to the shadow root instead of the document which caused some issues.
Some properties and methods of both PiP and fullscreen always have to be accessed on the `document` according to the docs:
https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API
https://developer.mozilla.org/en-US/docs/Web/API/Picture-in-Picture_API
> Add fixes for PiP and Fullscreen

- src/js/constants.js
- src/js/media-controller.js
When working on a custom poster experience I really found myself missing the `videojs-has-started` class. In the Media Chrome world that felt like it could be a `media-has-played` attribute that's `true` forever after the `playing` event fires for the first time. This is proposing a new attribute, so normally I'd go through a discussion first, but since this was so tiny I figured it was ok to put out there for feedback. 
How should I be thinking about testing this?
> Add media-has-played attribute

- examples/advanced.html
- examples/mobile.html
- src/js/constants.js
- src/js/media-airplay-button.js
- src/js/media-controller.js
- src/js/media-pip-button.js
- src/js/media-volume-range.js
This PR adds basic support for availability/support detection, as discussed in #134 
Currently implemented generic volume and airplay detection, with pending attributes for closed captions. Note there are still some decisions "around the edges" that have yet to be resolved.
Issuing this now to facilitate the conversation, start preliminary review, and potentially merge with the possibility of followup PRs to pin down any outstanding discussion points.
> feat/availability-states: Add support for availability detection and state management. Update advanced and mobile examples for demo purposes.

- src/js/media-container.js
Noticed this while I was testing something unrelated, but currently hovering over a playing stream that _doesn't_ have a poster image is broken.
> bugfix: fix hovering over an active controller with no poster

- examples/index.html
- examples/media-elements/jwplayer.html
- src/js/media-controller.js
Fixes https://github.com/muxinc/media-chrome/discussions/174
Adds the JW player video element (https://github.com/luwes/jwplayer-video-element) as an example.
Even made the controlbar thumb previews working but they're very tiny 120px. 
Might need to set a min width there to make them bigger but more blurry 🤷‍♂️
> Adds a JW player video element as example

- src/js/media-container.js
With mouseout, we would get an event each time we cross an element
boundary, meaning we could end up marking the player as inactive as a
user is mousing around in the player. Instead, we should use mouseleave
that would only trigger when we leave the entire element including its
children.
> fix: use mouseleave instead of mouseout

- src/js/media-container.js
- test/unit/media-theme.spec.js
This change adds support for swapping out slotted media slots aka `<slot name="media" slot="media"></slot>` which might come in useful when you'd like to switch a Media Theme but keep the same video element.
See the bug without this change here (click the Switch Theme button):
https://elements-demo-vanilla-git-fork-luwes-media-theme-mux-mux.vercel.app/mux-player.html
> Add support for media swapping in chained slots

- src/js/media-controller.js
Like we discussed in https://github.com/muxinc/media-chrome/pull/182#issuecomment-1067370339 the media controller shouldn't try to mimic the video API.
- This change removes all the getters that could be replaced with a getAttribute or hasAttribute
- Moves the getters that were used internally as helpers to private functions
- Removes all setters that can be replaced with an event dispatch on the controller
e.g. `controller.dispatchEvent(new Event(MEDIA_ENTER_FULLSCREEN_REQUEST));`
The goal is to remove duplication and confusion on which API should be used (media API vs controller API) and add this constraint so media controller doesn't try to do too much, become a player basically.
> Remove unneeded media like API

- examples/advanced.html
- examples/basic.html
- examples/media-elements/dash.html
- examples/media-elements/hls.html
- examples/media-elements/jwplayer.html
- examples/media-elements/mux-video.html
- examples/media-elements/wistia.html
- examples/media-elements/youtube.html
- examples/mobile.html
- examples/slots-demo.html
- examples/standalone-controls.html
- examples/state-change-events-demo.html
- examples/themes/demuxed-2021-theme.html
- examples/themes/spotify-theme.html
- examples/themes/youtube-theme.html
- src/js/media-container.js
Fixes #103
This change makes Media Chrome sizing based on the video element and behave the same.
It's a good thing I believe that the user is encouraged to set dimensions on Media Chrome because it will prevent cumulative layout shift. It's already too late for us to set default dimensions on Media Chrome internally because of the deferred nature of `<script type=module>`. A good example is to refresh the webpage a couple of times and see the difference between:
- https://media-chrome.mux.dev/examples/advanced.html
- https://media-chrome-git-fork-luwes-video-like-sizing-mux.vercel.app/examples/advanced.html
Look at the [View more examples](https://media-chrome.mux.dev/examples/) link or turn off javascript and compare.
Note that the default (with no video content) minimum video dimensions …
> Make MC sizing based on video element size

- src/js/media-time-display.js
media-time-display shows both the current or remaining time and the
duration separated by a slash. Around the slash, there are spaces, so,
when the control bar is small, this causes the element to wrap onto
multiple lines. This can cause unexpected styling issues with the
control bar.
The expectation of this element is to stay on one-line like the other
time displays.
While we could add this into media-text-display, it's already used for
non time displays in the examples, though, internally in media-chrome,
media-text-display is only used in the time displays.
Before:
After
:
> fix: make media-time-display not wrap when small

- examples/themes/netflix-theme.html
- src/js/index.js
- src/js/themes/media-theme-netflix.js
- src/js/themes/media-theme.js
This change exports the base MediaTheme class and adds a render method that can be overridden.
In the simplest case theme devs just provide a string template to their class that extends MediaTheme.
This change also fixes up the Netflix media theme and uses that in the examples. Good for testing.
```js
class MediaTheme extends HTMLElement {
static template = '';
constructor() {
super();
this.attachShadow({ mode: 'open' });
}
connectedCallback() {
this.render();
}
render() {
this.shadowRoot.textContent = '';
const template = document.createElement('template');
template.innerHTML = this.constructor.template;
// Clone the template in the shadow dom
this.shadowRoot.append(template.content.cloneNode(true));
// Expose the media controller if API access is needed
this.mediaController = …
```
> feat: export MediaTheme w/ overrideable render

- examples/advanced.html
- examples/basic.html
- examples/media-elements/hls.html
- examples/media-elements/jwplayer.html
- examples/media-elements/mux-video.html
- examples/media-elements/wistia.html
- examples/media-elements/youtube.html
- examples/mobile.html
- examples/slots-demo.html
- examples/standalone-controls.html
- examples/state-change-events-demo.html
- examples/themes/demuxed-2021-theme.html
- examples/themes/youtube-theme.html
- src/js/media-controller.js
- src/js/utils/element-utils.js
This change fixes an issue where if the media-controller was contained in multi-level shadow DOM the isFullscreen check would fail. 
Safari doesn't support ShadowRoot.fullscreenElement, the solution here uses document.fullscreenElement to check if any element in the document is fullscreen and then event.target to check if the target is contained or is itself the media-controller.
This PR also improves the contains utility function `containsComposedNode` to be more efficient.
> Fix isFullscreen check for deep shadow nesting

- docs/styling.md
- examples/index.html
- examples/vertical.html
- src/js/media-thumbnail-preview.js
- src/js/media-time-range.js
Related to https://github.com/muxinc/media-chrome/pull/171
Adds a configurable max and min width for the thumb preview.
This uses a CSS transform: scale() to up and down scale to the max and min width via JS if needed. A small down side is that the border also scales with that, this is solved by setting each CSS property again with the scale factored in with JS.
Also changed the positioning via `style.left` to `style.transform = translate` because this should perform better.
https://www.paulirish.com/2012/why-moving-elements-with-translate-is-better-than-posabs-topleft/
- bottom black border in thumb preview
- fading out animation did not work because of the CSS display prop
> Add max/min css vars for the thumb previews

- src/js/media-time-display.js
- src/js/media-time-range.js
Since refactoring to support seekable ranges, we can no longer "default" the duration values. Per suggestion from @luwes , for now we can just assign default values for less confusing visualization.
> Fix/default UI times

- examples/themes/netflix-theme.html
- src/js/media-time-range.js
Fixes an issue where the off range logic was called too early for Media Chrome in a shadow dom of another element.
> fix: mouseout timerange for deeply nest shadowdom

- src/js/media-time-range.js
On mobile, the preview requests don't happen properly due to the usage of `mousemove`. Switching to `pointermove` seems to help them come up properly.
> fix: switch to pointermove from mousemove for media preview request

- docs/react.md
- Correct `<MediaVolumeRange>` component spelling in under the _Components_ heading by adding missing letter, _m_
- Add missing punctuation
- Correct Markdown link syntax for linking to React `className` docs
> docs: correct spelling & grammar in React docs

- examples/advanced.html
- examples/basic.html
- examples/mobile.html
- examples/slots-demo.html
- examples/standalone-controls.html
- examples/state-change-events-demo.html
- examples/vertical.html
- src/js/media-container.js
This keeps desktop behavior for mobile/touch devices. When
tapping, it'll unhide the controls and then setup the timer to autohide.
`mousemove` triggers even when a user only does a single tap.
`pointermove` doesn't occur with just a single tap, so, we switch
`mousemove` to `pointermove`. Then, we schedule the inactivity timeout
on `pointerup` when `pointerType` is `touch`, since other pointer types
are covered.
> fix: unhide controls on touch & autohide on timer

- src/js/media-controller.js
fixes a bug where the cast button wouldn't hide because the unavailable attribute was not set.
> fix: cast unavailable bug

- .github/workflows/ci.yml
- package.json
- yarn.lock
Discussed in https://github.com/muxinc/media-chrome/discussions/239
Adds auto publish on the main branch with canary versions (`0.6.9-canary.0+17dac0e`) on the NPM `canary` release channel.
> ci: add canary command

- package.json
`npm view media-chrome versions --json | jq -r '.[-1]'` gets the last published version of all.
`npm view media-chrome@canary version` would only get from the `cananry` channel so that wouldn't work after a new release.
`sed -r 's/-[a-z0-9]{7}$//g'` strips the hash from the version because it would mess up the semver canary prerelease.
--- 
confirmed `jq` is installed in GH action 
https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md
> ci: fix canary version w/ SHA hash

- src/js/media-container.js
The gestures layer, depending on configuration, may add an extra 5
pixels above or below the control bar, which is unwanted. Instead, when
we're playing back audio, we should hide the gestures display, which
involves making it a block element so that we can set the height of it
to zero.
Setting the MC's background color to red, we can see that there's some extra pixels above or on the side.
One thought I had been to set the layers's display to be `inline-block`, but that causes some extra sizing issues:
So, decided to go with a more surgical approach and only target the issue at hand, which works like a charm:
> fix: hide gesture-layer when in audio mode

- src/js/media-controller.js
requires:
https://github.com/muxinc/elements/pull/253
https://github.com/muxinc/castable-video/pull/9
the event handlers are re-run at init so we need to be explicit.
fixes an issue where the cast button would not show in the Next.js app
> fix: cast availability

- .github/workflows/cd.yml
- CHANGELOG.md
- package.json
- scripts/publish.sh
- yarn.lock
this change adds a CD workflow to publish a release via GH actions. can choose between conventional, patch, minor, major.
already working in https://github.com/muxinc/castable-video
this is also more in line with Mux elements where we started using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
see https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-cli
> chore: add publish workflow

- .github/workflows/ci.yml
- package.json
- scripts/publish.sh
- yarn.lock
Made the dev dependencies install on the fly with npx since it's rarely called locally.
Made the shell script run without sourcing it first, added a `help` flag.
> ci: improve publish release script

- docs/styling.md
- examples/advanced.html
- examples/basic.html
- examples/control-elements/media-preview-thumbnail.html
- examples/control-elements/media-thumbnail-preview.html
- examples/index.html
- examples/themes/demuxed-2021-theme.html
- examples/themes/netflix-theme.html
- examples/themes/youtube-theme.html
- examples/vertical.html
- package.json
- src/js/constants.js
- src/js/extras/media-clip-selector/index.js
- src/js/index.js
- src/js/media-chrome-button.js
- src/js/media-chrome-range.js
- src/js/media-container.js
- src/js/media-control-bar.js
- src/js/media-controller.js
- src/js/media-gesture-receiver.js
- src/js/media-preview-thumbnail.js
- src/js/media-preview-time-display.js
- src/js/media-settings-popup.js
- src/js/media-text-display.js
- src/js/media-thumbnail-preview.js
- src/js/media-time-range.js
- src/js/themes/media-theme-youtube.js
- src/js/utils/element-utils.js
this allows users to add anything in the slots that they like to have moved with the boxes along side the time range.
---
New media-time-range nesting options with `preview` and `current` slot:
```html
<media-time-range>
<media-preview-thumbnail slot="preview"></media-preview-thumbnail>
<media-preview-time-display slot="preview"></media-preview-time-display>
<media-current-time-display slot="current"></media-current-time-display>
</media-time-range>
```
--- 
TODO: update docs with all the new CSS vars
> feat: improve time range behavior

- README.md
- examples/basic.html
- examples/themes/spotify-theme.html
- Upgrade Media Chrome CDN links to v0.7.0
- Fix the audio source urls.
- Improve the Spotify player theme example with the new time preview
> fix: MC v0.7.0, audio examples, spotify example

- src/js/media-time-range.js
just noticed this issue where the smooth progress becomes jumpy with a playback rate other than 1.
> fix: timerange progress jumpy w/out playback rate

- examples/casting.html
- examples/index.html
- examples/vtt/bbb-en-cc.vtt
Adds an Google casting example to the examples site 
Requires https://github.com/muxinc/castable-video
I chose to add BBB here because somehow Chromecast didn't like the Mad Max progressive mp4 🤷‍♂️ (stuttering)
> docs: add Chromecast / Google Cast example

- docs/media-controller.md
- src/js/media-chrome-button.js
- src/js/media-chrome-range.js
- src/js/media-container.js
- src/js/media-controller.js
Kicking off the work for https://github.com/muxinc/media-chrome/discussions/257
> feat: initial keyboard shortcut support

- src/js/media-time-range.js
When playback stalls (because the backing media player fails to buffer quickly enough), the progress bar would incorrectly keep advancing. This fixes that, stopping the progress bar from advancing while the media is loading.
> Stop progress bar when media is loading

- src/js/media-chrome-button.js
- src/js/media-controller.js
For keyboard shortcuts and media-chrome-button, we add a keyup handler on keydown to make it more reliable to recognize and disambiguate between keys used standalone (`k`) or with modifiers (`ctrl-k`). In addition, this gives us the ability to have cancellable behavior, by allowing users to press `esc` to prevent the action from happening since the `keyup` handler is removing on a `keydown` of a disallowed key like `esc`.
However, what happens if you keep an allowed key pressed, but then press a second allowed key? Currently, the behavior of the second key will trigger and the behavior of the first key will trigger depending on how quickly it is released. So, if a user pressed `k` to toggle playback but kept holding it down and then pressed `f`, the media-chrome will toggle fullscreen. If …
> fix: keyup handlers for some keyboard behavior should only apply once

- src/js/media-container.js
related #301
setting any element to `display: none` in the gesture-layer will disable gestures on that element.
> fix: `gestures-disabled` attribute

- src/js/media-container.js
This change adds the correct order of the chrome containers so a11y tab order improves going from the top chrome elements to the center chrome elements and then to the bottom chrome elements.
Before it went from top -> bottom -> center 
This change makes use of disabling the CSS `display: contents` property on some `<slot>` elements essentially making them visible containers.
In addition some CSS parts were added for the different chrome sections which we'll be able to use in Mux Player.
> feat: fix order of layers + add chrome CSS parts

- src/js/media-container.js
- src/js/media-gesture-receiver.js
- src/js/utils/element-utils.js
this change fixes a bug where the gestures were picked up on the controls itself.
I also took the time to instead of listening on the window listen on the media controller because it feels a bit safer / local.
currently the allowList is not extensive and could potentially be extended. 
I thought of a "video element" that wouldn't use a native "video" element under the hood.
maybe better to check if the element is just in the media slot?
> fix: gesture captured on controls bug

- src/js/media-controller.js
The first pass is how I'd expect to handle PiP-not-ready errors.
Assume where `alert()`s happen, it means:
1. log to the console for the media chrome developer
3. propagate a [currently undefined] error state that an error display component could use to inform the viewer what's happening
There's a few decisions baked in:
1. Don't assume the media has the needed APIs to avoid the error (readyState in this case)
2. When it does have the API, use it, and make viewer-friendly error messaging possible
4. If the error can't be avoided (e.g. readyState isn't supported), handle known errors triggered by the viewer (InvalidStateError in this case) and make viewer friendly error messaging possible. 
5. Don't silence unknown errors from the media element
Thoughts on all that?
> POC of handling media errors in media chrome

- docs/src/pages/en/keyboard-shortcuts.md
- src/js/media-captions-button.js
- src/js/media-controller.js
- src/js/utils/captions.js
Adds a `c` hotkey to toggle captions.
This uses method delegation to the `MediaCaptionsButton`'s `handleClick` method because there's a lot of code there.
~Needs a quick addition to docs still, but also, due to the recent media-gestures-receiver change, the player doesn't get focus when click on the video element and thus keyboard shortcuts don't work there. Though, might want a fix for that separately from this.~
> feat: add a hotkey for toggling captions: c

- src/js/media-container.js
- src/js/media-controller.js
This is so that clicking inside the player gets focus changed to be inside the player and hotkeys work as expected. If a tabindex is already set, we shouldn't override it. Otherwise, we should set it to be -1 so that clicking would change focus but it wouldn't be added to the regular tab order.
Since the primary usecase of this is for hotkeys, there will be keyboard interactions with the player after the focus change. However, this does mean that an outline will be added to the media element. This probably isn't an issue when windowed, but in fullscreen, we definitely don't want an outline border on the media.
Fixes #309
> fix: set tabindex on media element, if not set

- src/js/media-controller.js
This implements the TODO to automatically propagate all state. Uses a delegate object that matches the MediaUIAttributes in case we need to do something special, otherwise, it'll use the `default` method which returns the attribute's value.
> refactor: delegate all media ui attributes

- package.json
- src/js/media-airplay-button.js
- src/js/media-captions-button.js
- src/js/media-cast-button.js
- src/js/media-chrome-button.js
- src/js/media-chrome-range.js
- src/js/media-container.js
- src/js/media-control-bar.js
- src/js/media-fullscreen-button.js
- src/js/media-mute-button.js
- src/js/media-pip-button.js
- src/js/media-text-display.js
- src/js/media-time-range.js
- src/js/media-title-element.js
- remove minify and sourcemap options from the esm and cjs bundles. these are all separate files (not bundled) so it makes less sense to minify and add sourcemaps for each file. these files are expected to be bundled by the consumer.
- adds a esm-module bundle, was mainly for getting a accurate gzip bundle size but just thought the iife could also be used for that?
- put the comments in expressions so these can be easily removed by bundlers. golfed down -1.3kB with this 🥳
> feat: remove minify/srcmap esm/cjs, add esm-module

- docs/src/pages/en/styling.md
- src/js/media-poster-image.js
Related to https://github.com/muxinc/elements/issues/444
adds positioning and size / fit css vars for the `media-poster-image` element
> feat: add poster object fit and position css vars

- src/js/media-container.js
If a user presses play but doesn't move the mouse out of the control bounds, the controls never autohide. Instead, we should schedule inactive when a click happens. Then, on pointermove automatic hiding would be prevented as usual.
Mobile behavior of toggling controls is maintained as well.
Fixes #188
> fix: clicking in media-container should schedule inactive

- src/js/media-time-range.js
this fixes an issue when configuring a bounds for the previews in shadow dom
> fix: preview bounds in shadow dom

- README.md
- docs/src/pages/en/get-started.md
- examples/casting.html
- examples/media-elements/dash.html
- examples/media-elements/hls.html
- examples/media-elements/jwplayer.html
- examples/media-elements/media-playlist.html
- examples/media-elements/mux-video.html
- examples/media-elements/videojs.html
- examples/media-elements/vimeo.html
- examples/media-elements/wistia.html
- examples/media-elements/youtube.html
- examples/themes/youtube-theme.html
main reason being they provide pkg download stats but it's also more feature rich overall, faster and less downtime I imagine
https://www.jsdelivr.com/package/npm/media-chrome
[![](https://data.jsdelivr.com/v1/package/npm/media-chrome/badge)](https://www.jsdelivr.com/package/npm/media-chrome)
https://www.jsdelivr.com/network
> tools: move from unpkg.com to jsdelivr.com

- src/js/media-chrome-range.js
- src/js/media-time-range.js
- src/js/utils/element-utils.js
Related #281
- fixes a `--media-range-track-border` double border bug on the chrome range
- adds a `--media-range-track-outline` and `--media-range-track-outline-offset`
- fixes the time range current time box using percentages which repositions on player resize 
that was a tricky one but it makes the code simpler overal though introduces 1 wrapper div#container
> fix: box percentage positioning & time range border glitch

- src/js/constants.js
- src/js/media-chrome-button.js
- src/js/media-chrome-range.js
- src/js/media-control-bar.js
- src/js/media-controller.js
- src/js/media-gesture-receiver.js
- src/js/media-loading-indicator.js
- src/js/media-preview-thumbnail.js
- src/js/media-text-display.js
Fixes #366 
The media-controller attribute on UI components stopped working at some point, and it appears to be because the attribute was being lumped in with all the state attributes. I think that was having a few weird side effects, but the result was the button's media-controller attribute was getting reset to nothing by the media controller, then causing the button to unregister itself from the media controller (which was only half working. The play request event was still working after being unregistered. So something maybe worth digging more into).
> Fix mc attr

- src/js/media-theme-element.js
- src/js/themes/media-theme-netflix.js
Similar to @heff 's comment https://github.com/muxinc/media-chrome/pull/362#discussion_r1034168845
I think maybe an extends makes sense here with a static `template` property.
> fix: add a way to package media themes as web comp

- examples/control-elements/media-captions-listbox.html
- examples/control-elements/media-chrome-listbox.html
- examples/control-elements/media-chrome-menu-button.html
- examples/index.html
- src/js/media-chrome-listbox.js
- src/js/media-chrome-menu-button.js
Adds a media-chrome-menu-button that mostly does what we expect. Not sure if menu-button is necessarily the best name, but it works. Happy to change it, though.
Usage:
```html
<media-chrome-menu-button aria-label="captions menu button">
<svg slot="button-content" aria-hidden="true" viewBox="0 0 26 24"></svg>
<media-captions-listbox slot="listbox" media-controller="mc"></media-captions-listbox>
</media-chrome-menu-button>
```
The next simple follow-up is a captions-menu-button that basically wraps up this above usage in a prepackaged component.
There's still some more follow up to do as per #387. With a new Off menu item, and to make it more accessible, we may want to update listbox to be able to be a role of menu instead of listbox with a listitem a role of menuitem over options.
Those …
> media-chrome-menu-button

- examples/responsive-attribute.html
- examples/responsive.html
- src/js/constants.js
- src/js/media-container.js
test url: https://media-chrome-git-fork-luwes-resize-observer-mux.vercel.app/examples/responsive-attribute.html
- removed the media-container-size attribute
- added attributes for the breakpoints: `breakpoint-sm`, `breakpoint-md`, `breakpoint-lg` and `breakpoint-xl`
- added attribute `breakpoints` for customizing breakpoints. e.g. `breakpoints="sm:300 md:400 lg:500"`
> feat: container-size attr w/ range naming

- examples/experimental/themes/youtube-theme.html
- src/js/media-theme-element.js
- src/js/themes/media-theme-demuxed-2022.js
- src/js/utils/template-processor.js
- test/unit/template-processor.spec.js
- adds `>`, `>=`, `<`, `<=` operators
- add the `media-stream-type` attribute to the available theme props as `streamType`
For a logical AND we decided to use nested `if` templates instead of supporting more complex expressions like in #383
> fix: template syntax & add streamType to template props

- docs/src/config.ts
- docs/src/layouts/MainLayout.astro
- docs/src/pages/en/themes.md
This adds a first pass of the Themes documentation. It's still a work in progress but any tips or feedback welcome.
https://media-chrome-docs-git-fork-luwes-docs-themes-mux.vercel.app/en/themes
> docs: Media Chrome Themes docs

- src/js/media-theme-element.js
fixes an issue where a removal of an attribute on the media-theme element would not trigger a render.
> fix: render on all attr changes, also removal

- src/js/media-theme-element.js
- src/js/themes/media-theme-demuxed-2022.js
- src/js/themes/media-theme-netflix.js
- src/js/themes/media-theme-responsive.js
- src/js/themes/media-theme-winamp.js
- src/js/themes/media-theme-youtube.js
this is required for (Mux Player) React because sometimes the `media-theme` element is not upgrade yet so the template property will be set on an HTMLElement. After the upgrade we have to re-set it on the instance of the custom element...
https://web.dev/custom-elements-best-practices/#make-properties-lazy
> fix: add lazy template prop to theme el

- src/js/media-theme-element.js
turns out the template in the theme element has to be rendered on construction so that the controller is available right away.
otherwise we get an error `<media-controller> failed to upgrade!`
> fix: create theme template on construction

- src/js/media-controller.js
Was seeing a bunch of uncaught promise rejects in tests and realized it stemmed from here. We should be catching this rejected promise as it happens internally and isn't actionable by users of media-chrome.
> fix: catch play promise internally

- src/js/media-controller.js
Since `"unknown"` is supposed to represent cases where the slotted media element supports the `streamType` [media-ui-extension](https://github.com/video-dev/media-ui-extensions/issues/3) but cannot derive the stream type yet, updating impl to prefer `default-stream-type` in this case.
> fix: Use default-stream-type when slotted media streamType is unknown.

- src/js/media-chrome-button.js
- src/js/media-chrome-range.js
- src/js/media-control-bar.js
- src/js/media-gesture-receiver.js
- src/js/media-loading-indicator.js
- src/js/media-preview-thumbnail.js
- src/js/media-text-display.js
- src/js/media-time-display.js
- test/unit/media-controller.spec.js
- test/unit/media-theme.spec.js
This change fixes an issue with using media controls that are not nested in `media-controller` but connect via the `id` and `media-controller` attribute in the context of a shadow DOM.
The bug is that `document.getElementById` doesn't search in shadow DOM.
The fix implemented here is to use `this.getRootNode().getElementById`. This only works when connected to the DOM.
> fix: decoupled controller in media-theme

- src/js/media-theme-element.js
- src/js/themes/micro.js
while I was writing the theme docs I noticed the multi-layout theme has very little styles
https://media-chrome-docs-git-fork-luwes-theme-docs-mux.vercel.app/en/themes/responsive-themes
should it have any styles at all to get this functionality came to mind?
maybe proper defaults makes sense in the base theme, it's always possible to override them.
> fix: add default much used styles to theme

- src/js/utils/template-processor.js
- test/unit/template-processor.spec.js
this change was mainly to fix an issue with the regex of the nullish coalesce operator that @cjpillsbury found.
instead of tweaking the regex I did a small refactor so all expressions are now run through the same tokenizer and evaluator.
this should be more robust, having 1 location for matching the tokens.
> fix: nullish coalesce operator, improve process

- src/js/constants.js
- src/js/media-controller.js
- src/js/media-theme-element.js
This ensures that `<media-controller>`'s state representation for `streamType` and `targetLiveWindow` are more predictable, even for cases where the slotted media element has no/partial support for these media-ui-extension values. This will allow for more predictable UI design, including (especially) with Media Chrome themes.
> Fix/improve inferred media-ui-extension values

- examples/themes/responsive-theme.html
- src/js/media-theme-element.js
- src/js/themes/responsive.js
Made the responsive theme example show a similar state with the basic example for comparison.
`media-theme-element` actually needed a default of `display: inline-block` to match with theme-less out of the box.
Basic: https://media-chrome-git-fork-luwes-responsive-theme-tweaks-mux.vercel.app/examples/basic.html
Theme: https://media-chrome-git-fork-luwes-responsive-theme-tweaks-mux.vercel.app/examples/themes/responsive-theme.html
if the media-theme-element was `display: block` by default the audio player would expand 100% in the theme example
> fix: theme inline-block, improve responsive theme

- examples/advanced.html
- examples/basic.html
- examples/casting.html
- examples/disabled.html
- examples/experimental/themes/responsive-theme.html
- examples/media-elements/jwplayer.html
- examples/responsive-attribute.html
- examples/responsive-polyfill.html
- examples/responsive.html
- examples/state-change-events-demo.html
- examples/vertical.html
- src/js/themes/responsive.js
this attribute is unneeded as far as I can tell. it will be propagated by the waiting event 
https://github.com/muxinc/media-chrome/blob/90281290051c00acc95013ed82c712c77f4229e9/src/js/media-controller.js#L504-L507
> example: remove unneeded media-loading attr

- src/js/media-chrome-button.js
- src/js/media-chrome-range.js
- src/js/media-control-bar.js
- src/js/media-gesture-receiver.js
- src/js/media-loading-indicator.js
- src/js/media-poster-image.js
- src/js/media-preview-thumbnail.js
- src/js/media-text-display.js
this adds CSS vars for the control's `display` property.
it's handy for when using a theme to show/hide specific controls.
```html
<media-theme-responsive style="--media-fullscreen-button-display: none"></media-theme-responsive>
```
a theme or player can also easily create higher level CSS vars by forwarding
```css
media-controller::part(top) {
--media-play-button-display: var(--top-controls, var(--top-play-button, inline-flex));
--media-mute-button-display: var(--top-controls, var(--top-mute-button, inline-flex));
}
```
> fix: add display CSS vars

- examples/experimental/themes/micro-theme.html
- examples/experimental/themes/micro.html
- src/js/media-theme-element.js
- src/js/themes/demuxed-2022.js
Test URL: https://media-chrome-git-fork-luwes-theme-template-src-mux.vercel.app/examples/experimental/themes/micro-theme.html
this change adds support for fetching HTML files as theme templates.
this works better than I expected with the discovery of `link[rel=preload][as=fetch]`.
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/preload#what_types_of_content_can_be_preloaded
I initially thought it required the unsupported `as=document` or HTML imports.
The preloading is not required but it helps with showing the whole theme because only after the JS is loaded and executed can it start fetching the HTML file without any hints.
as you can see in the example both a local and remote url work.
it does require `access-control-allow-origin: *` in the response of the remote HTML …
> feat: support fetching theme HTML files

- examples/experimental/themes/microvideo.html
- src/js/themes/microvideo.js
- adds `media-loading-indicator`
- adds a poster slot
having a poster slot instead of an already defined `media-poster-image` element gives the most flexibility and promotes progressive enhancement, related to https://github.com/muxinc/media-chrome/issues/380
⚠️ for the first version I'd like to keep the more simple `media-captions-button` in this theme because with the control-bar placement it's not as straightforward to position the opened selectmenu
> fix: add poster slot, media loading indicator to Microvideo

- src/js/themes/minimal.js
Related to https://github.com/muxinc/media-chrome/pull/492
can be enabled with 
`--media-pip-button-display: inline-flex`, `--media-seek-forward-button-display: inline-flex`, etc...
> fix: add non-default buttons to Minimal theme

- examples/themes/microvideo-theme.html
- src/js/media-theme-element.js
- src/js/themes/microvideo.js
- src/js/themes/minimal.js
- src/js/utils/template-processor.js
- test/unit/template-processor.spec.js
this adds support for a negation `!targetLiveWindow` in themes.
it's required as that variable can be either `undefined` or `0` in the condition 
`<template if="targetLiveWindow == 0 or null ">`
> fix: add support for negations

- src/js/media-time-display.js
Discussion: https://github.com/muxinc/media-chrome/discussions/181
> fix: toggle time display on click from remaining / not remaining

- src/js/media-current-time-display.js
- src/js/media-duration-display.js
- src/js/media-preview-time-display.js
- src/js/media-text-display.js
- src/js/media-time-display.js
this change removes the unneeded container span and public container property from the text display elements and uses the slot and private slot property to add the content.
> fix: slot for text display, customizable content

- src/js/experimental/media-chrome-selectmenu.js
- src/js/media-chrome-button.js
- src/js/utils/server-safe-globals.js
This makes preventClick apply to keypresses in media-chrome-button.
It also has selectmenu listen to keypress events on the button and the listbox so that it can open and close the menu as expected via Enter/Space and Escape.
> fix: toggle selectmenu via keyboard

- examples/experimental/themes/microvideo-theme.html
- examples/experimental/themes/microvideo.html
- src/js/media-theme-element.js
- src/js/themes/demuxed-2022.js
- test/unit/media-theme.spec.js
this change fixes a bug where if the media-theme element was not added to the document yet it would throw a type error.
- adds support for rendering the template on connectedCallback if it didn't happen yet
- makes the template URL fetching a bit more strict on valid URL's so it doesn't try to request on just word URL's
it requires a `/` somewhere in the URL. `./`, `/`, `https://`
> fix: media-theme element lazy doc append

- package.json
- scripts/custom-elements-manifest.config.js
- yarn.lock
this fixes the issue that Justin brought up that the import urls should point to the consumable custom element files which are in the dist folder.
> fix: custom element manifest imports from dist/

- src/js/experimental/media-chrome-listbox.js
- src/js/experimental/media-chrome-listitem.js
- src/js/experimental/media-chrome-selectmenu.js
- src/js/extras/media-clip-selector/index.js
- src/js/media-chrome-button.js
- src/js/media-chrome-range.js
- src/js/media-container.js
- src/js/media-control-bar.js
- src/js/media-gesture-receiver.js
- src/js/media-loading-indicator.js
- src/js/media-poster-image.js
- src/js/media-preview-thumbnail.js
- src/js/media-text-display.js
- src/js/media-theme-element.js
Related #184
This makes Media Chrome DSD compatible in case anyone is putting in declarative shadow dom.
It creates shadow DOM without any JS needed. See example:
```html
<host-element>
<template shadowrootmode="open">
<slot></slot>
</template>
<h2>Light content</h2>
</host-element>
```
Supported now by Chrome and Safari 16.4! 
https://developer.chrome.com/en/articles/declarative-shadow-dom/
https://webkit.org/blog/13966/webkit-features-in-safari-16-4/#web-components
> fix: make DSD (declarative shadow dom) compatible

- docs/package.json
- package.json
- scripts/custom-elements-manifest.config.js
- yarn.lock
Related #388 
Adds a `vscode.html-data.json` file generated from the custom-elements.json.
https://github.com/microsoft/vscode-custom-data
> VS Code ships with rich [language feature support](https://code.visualstudio.com/api/language-extensions/programmatic-language-features) for HTML/CSS, such as auto-completion and hover information. The core of these language support are implemented in [vscode-html-languageservice](https://github.com/microsoft/vscode-html-languageservice) and [vscode-css-languageservice](https://github.com/microsoft/vscode-css-languageservice). In the past, these libraries were coupled to outdated schemas that define HTML/CSS entities. Custom data decouples these libraries from the data they use and allows VS Code to offer up-to-date support for latest HTML/CSS …
> chore: add vscode custom data / autocomplete

- src/js/experimental/media-chrome-listbox.js
- src/js/media-chrome-button.js
- src/js/media-text-display.js
this glitch has been bugging us for a while and today I saw it in the Mux blog post again. had to do a quick fix attempt.
the issue is that the font Arial has not the same width for each number the number `1` for example is more narrow making the time display jump left right and making the time range or volume range also jump. that sucks!
I did a bunch of tests, `font-variant-numeric: tabular-nums;` doesn't work for Arial unfortunately.
luckily the default `Helvetica Neue` that is supported on all MacOS and iOS has even width numbers.
Also Helvetica Neue looks very similar to Arial so it seemed like an okay solution.
no more jumpy time codes!
for example check these examples and let play until -0:11
Old: https://media-chrome.mux.dev/examples/vanilla/vertical.html
New: …
> fix: font numeric uniform width

- docs/src/layouts/MainLayout.astro
- docs/src/pages/en/media-playback-rate-selectmenu.md
- examples/vanilla/control-elements/media-chrome-selectmenu.html
- src/js/experimental/media-captions-listbox.js
- src/js/experimental/media-chrome-listbox.js
- src/js/experimental/media-chrome-selectmenu.js
- src/js/experimental/media-playback-rate-listbox.js
- src/js/experimental/media-playback-rate-selectmenu.js
- src/js/media-playback-rate-button.js
- src/js/utils/captions.js
This uses a playback-rate-listbox under the hood which accepts items *declaratively* only.
```html
<media-playback-rate-listbox media-controller="mc">
<media-chrome-listitem value="1">1x</media-chrome-listitem>
<media-chrome-listitem value="1.5">1.5x</media-chrome-listitem>
<media-chrome-listitem value="2">2x</media-chrome-listitem>
<media-chrome-listitem value="3">3x</media-chrome-listitem>
</media-playback-rate-listbox>
```
The selectmenu itself accepts a `rates` property like the `playback-rate-button` does. It also defaults to the same defaults.
```html
<media-playback-rate-selectmenu rates="1 2 3 4"></media-playback-rate-selectmenu>
```
This also has some updates to the main listbox class such has the `value` getter/setter, which is available on the HTMLSelectElement as a both as …
> feat: introduce a playback rates selectmenu

- src/js/media-theme-element.js
- src/js/themes/microvideo.js
- src/js/themes/minimal.js
- src/js/themes/responsive.js
- test/unit/media-controller.spec.js
I had hoped we could add this CSS to media-container but it's not possible :( 
because those control elements are in the light DOM which could be nested in divs and not reachable via CSS in the shadow DOM.
still nice to have out of the box for themes I think.
> fix: add default unavailable CSS to themes

- docs/src/components/LeftSidebar/LeftSidebar.astro
- docs/src/layouts/MainLayout.astro
- docs/src/styles/index.css
- docs/src/styles/theme.css
- fix color contrast of left sidebar selection
- align more to Mux docs sidebar styles
> docs: fix contrast + sidebar style

- src/js/media-time-display.js
- src/js/utils/element-utils.js
This is a first pass at defining getters and setters for all defined attributes. There's also JSDoc comments with the correct types.
I've used the attribute values themselves as the source of truth of the values which simplifies copying values back and forth between attributes and props.
Additionally, the public `mediaSeekableEnd` and `mediaSeekableStart` methods have been removed. These where undocumented and added to the public API of the component but where only used as utilities internally. We can add them back if we think they would be useful and document their usage.
If you set `remaining` or `showDuration` via a setter, the UI updates expectedly. If you set `mediaCurrentTime` the UI does update but the media doesn't actually seek. Clicking play for instance will reset the current …
> feat: Add missing attr getters and setters for media-time-display

- src/js/media-control-bar.js
Fixes regression from previous update to auto-size (height) ranges in control bar like other components. This makes sure we don't do that if there are only media chrome ranges as descendants.
> fix: don't auto-size ranges in media-control-bar if they're all alone.

- src/js/media-airplay-button.js
- src/js/media-captions-button.js
- src/js/media-cast-button.js
- src/js/media-time-display.js
- src/js/utils/element-utils.js
Adds missing props for the Airplay, Captions, and Cast buttons.
With captions specifically, we have to decide on the prop type for getting and setting a subtitles list. This is currently a simple array of strings. This matches how we store and retrieve the data from the attribute and also makes interacting with the prop similar to how a dev would interact with the attribute directly.
The alternative is to accept `TextTrack`'s (or objects that are a subset with only the data we need). Is this preferable? I can see this being simpler for the developer assuming they have `TextTrack`'s at hand.
> feat: Airplay, Captions, and Cast button props

- src/js/media-captions-button.js
Fixes a utility in the captions button component that wasn't comparing old and new values properly.
> fix: Comparison of text track lists

- docs/src/config.ts
- docs/src/pages/en/prevent-layout-shift.md
removes the sidebar category `core concepts`
> docs: remove core concepts and move pages

- src/js/media-poster-image.js
- src/js/media-preview-thumbnail.js
- src/js/media-preview-time-display.js
Adds missing props for Poster Image, Preview Thumbnail, and Time Display components.
> feat: Poster Image, Preview Thumbnail, and Time Display props

- src/js/media-pip-button.js
- src/js/media-play-button.js
- src/js/media-playback-rate-button.js
- src/js/utils/attribute-token-list.js
Adds missing props.
Also fixes the playback rate click handler which seemed to not work on page load where `_rates` was undefined and would throw an error. Falls back to DEFAULT_RATES correctly now.
> feat: Pip button, Play button, and Playback Rates props

- .github/workflows/cd.yml
- scripts/publish.sh
In release script:
- add --dry-run option
- add --tag option for npm dist-tag release channel, default to `latest`
- add internal release_type variable
In CD script
- add new tag_type required option, default to `latest`
- pass this as a --tag flag to the publish scripts
> chore: release script and CD updates

- src/js/themes/microvideo.js
- src/js/themes/minimal.js
- src/js/themes/responsive.js
- src/js/themes/winamp.js
- Fixes lingering `kebab-case` attrs in theme definitions.
- Renames theme-specific attributes as `lowercase` instead of `kebab0case` for consistency (e.g. `seek-forward-offset` is now `seekforwardoffset`)
> fix: Update official themes to use lowercase attrs consistently.

- docs/astro.config.mjs
- docs/src/components/PageContent/CopyToClipboard.astro
- docs/src/components/Sandpack.jsx
- docs/src/components/SandpackContainer.astro
- docs/src/layouts/MediaElementLayout.astro
- docs/src/pages/en/components/media-captions-button.mdx
- docs/src/pages/en/components/media-cast-button.mdx
- docs/src/pages/en/components/media-fullscreen-button.mdx
- docs/src/pages/en/components/media-live-button.mdx
- docs/src/pages/en/components/media-loading-indicator.mdx
- docs/src/pages/en/components/media-mute-button.mdx
- docs/src/pages/en/components/media-pip-button.mdx
- docs/src/pages/en/components/media-play-button.mdx
- docs/src/pages/en/components/media-poster-image.mdx
- docs/src/pages/en/components/media-seek-backward-button.mdx
- docs/src/pages/en/components/media-seek-forward-button.mdx
- docs/src/pages/en/components/media-time-display.mdx
- docs/src/pages/en/components/media-time-range.mdx
- docs/src/pages/en/components/media-volume-range.mdx
- docs/src/pages/en/get-started.mdx
- docs/src/pages/en/media-elements/hls-video.mdx
- docs/src/pages/en/media-elements/mux-video.mdx
- docs/src/pages/en/media-elements/spotify-audio.mdx
- docs/src/pages/en/media-elements/videojs-video.mdx
- docs/src/pages/en/responsive-controls.mdx
- docs/src/pages/en/styling.mdx
- docs/src/styles/index.css
- docs/src/styles/theme.css
- docs/src/styles/toggle.css
Test url: https://media-chrome-docs-git-fork-luwes-improve-sandpack-style-mux.vercel.app/en/media-elements/vimeo-video
- makes code highlighting in dark mode uniformer
- moves style closer to Mux docs code blocks, remove border-radius, dimmed background color
- moved to use previewAspectRatio instead of a fixed height
- made copy to clipboard icon nicer
> docs: improve Sandpack styles

- docs/src/pages/en/components/media-captions-button.mdx
- docs/src/pages/en/components/media-cast-button.mdx
- docs/src/pages/en/components/media-fullscreen-button.mdx
- docs/src/pages/en/components/media-pip-button.mdx
- docs/src/pages/en/components/media-play-button.mdx
- examples/vanilla/animated-icons.html
- src/js/media-captions-button.js
- src/js/media-cast-button.js
- src/js/media-fullscreen-button.js
- src/js/media-pip-button.js
- src/js/media-play-button.js
Adds an optional `icon` slot to buttons with multiple available slots e.g. Captions, Cast, Fullscreen, PiP and Play.
Updates docs with basic examples of usage. There's also a new `animated-icons.html` in the examples folder but this also currently has very basic examples to allow us to check the slots work as expected. We can expand this in the future with fancier animated demos.
> feat: Icon slots for buttons with multiple slots

- src/js/media-chrome-range.js
- src/js/media-time-range.js
Fixes https://github.com/muxinc/media-chrome/issues/656
As it turned out, input[type=range] makes half the width of thumb a "dead zone" where the value is either max or min. If we account for that when calculating preview values, we get the "right" result in preview. On a video of 3 minutes, the difference is < 0.01s between preview and input value.
> fix: time range preview and value inconsistency

- src/js/media-container.js
- src/js/utils/server-safe-globals.js
Ensures we do not end up with loop limit exceeded RTEs when breakpoints computations take too long.
> fix: Make computation for breakpoints in ResizeObserver async.

- scripts/react/build.js
not a biggie it seems but children are spread in the React.createElement function signature
https://react.dev/reference/react/createElement
> fix: React createElement function signature

- src/js/media-playback-rate-button.js
A playback rate of `10` was being sorted wrong. Thanks `sort()`!
> fix: Playback rate sorting for double digits

- package.json
related #680
allows to use `media-chrome/dist/react` as import 
this issue came up after adding support for CJS in https://github.com/muxinc/media-chrome/pull/650
Typescript types seem to still be broken for the new import path `media-chrome/react`
https://github.com/muxinc/media-chrome/pull/672
> fix: media-chrome/dist/react import

- src/js/media-live-button.js
`setAttribute` was accidentally used in the constructor. I've moved the logic to a function similarly to other elements.
> Fixes `<media-live-button/>`

- package.json
fix #680 
Thanks for adding exports declarations for EMS and CJS!  I was testing [the v1.x version of this package in the sanity-plugin-mux-input plugin](https://github.com/sanity-io/sanity-plugin-mux-input/pull/285) and TypeScript was having problems with `import { ... } from 'media-chrome/react'` which stemmed from problems with type resolution.
The solution I came across was adding in these `typesVersions` declarations which routes type resolution for react vs non-react imports to the expected files under `dist` to match what's declared under the `exports` field.
> Add typesVersions in package.json

- docs/src/pages/docs/en/reference/styling.astro
Fixes #701 by correcting the component relative path.
[Direct preview link to relevant page](https://media-chrome-docs-git-fork-derikolsson-docs-fix-styl-86641d-mux.vercel.app/docs/en/reference/styling)
> docs: fix component docs links on Styling Reference page

- src/js/media-container.js
`_inactiveTimeout` was incorrectly typed to `NodeJS.Timeout` which made my linter unhappy.
Either `number` or `ReturnType<typeof setTimeout>` would work but the latter feels more explicit.
> chore: Define the type of `_inactiveTimeout` so it is not inferred as `NodeJS.Timeout`

- examples/vanilla/control-elements/media-captions-listbox.html
- examples/vanilla/control-elements/media-playback-rate-listbox.html
- examples/vanilla/control-elements/media-playback-rate-selectmenu.html
- examples/vanilla/index.html
- src/js/experimental/index.js
- src/js/experimental/media-captions-listbox.js
- src/js/experimental/media-captions-selectmenu.js
- src/js/experimental/media-chrome-listbox.js
- src/js/experimental/media-chrome-option.js
- src/js/experimental/media-chrome-selectmenu.js
- src/js/experimental/media-playback-rate-listbox.js
- src/js/experimental/media-playback-rate-selectmenu.js
- src/js/experimental/media-rendition-button.js
- src/js/experimental/media-rendition-listbox.js
- src/js/experimental/media-rendition-selectmenu.js
- src/js/media-captions-button.js
- test/unit/media-chrome-listbox.spec.js
Based on https://github.com/muxinc/media-chrome/pull/683 needs to be merged first!
test urls:
- https://media-chrome-git-fork-luwes-checkmark-mux.vercel.app/examples/vanilla/control-elements/media-rendition-listbox.html
- https://media-chrome-git-fork-luwes-checkmark-mux.vercel.app/examples/vanilla/control-elements/media-captions-selectmenu.html
- https://media-chrome-git-fork-luwes-checkmark-mux.vercel.app/examples/vanilla/control-elements/media-playback-rate-listbox.html
> feat: add checkmark icon to listboxes

- examples/vanilla/control-elements/media-playback-rate-listbox.html
- src/js/experimental/media-chrome-selectmenu.js
when opening the select list keyboard focus wouldn't jump from button to list.
removing the fade in duration of visibility fixed this.
> fix: select keyboard focus

- src/js/utils/time.js
this was recently introduced with the NaN return value in getNumericAttr I think.
it looks pretty bad sometimes https://media-chrome.mux.dev/examples/vanilla/mobile.html
> fix: -:-- time codes on player load to 0:00

- examples/vanilla/control-elements/media-chrome-listbox.html
- examples/vanilla/control-elements/media-playback-rate-listbox.html
- examples/vanilla/control-elements/media-playback-rate-selectmenu.html
- examples/vanilla/control-elements/media-rendition-selectmenu.html
- src/js/experimental/media-captions-listbox.js
- src/js/experimental/media-chrome-listbox.js
- src/js/experimental/media-chrome-option.js
- src/js/experimental/media-chrome-selectmenu.js
- src/js/experimental/media-playback-rate-listbox.js
- src/js/experimental/media-rendition-listbox.js
- adds a header slot to listbox + example
https://media-chrome-git-fork-luwes-listbox-fixes-mux.vercel.app/examples/vanilla/control-elements/media-rendition-selectmenu.html
- adds a border-radius CSS var for listbox
- adds default font and color styles to the selectlist
- moves the `Auto` option to the bottom
- fixes an issue using the media-chrome-listbox as standalone 
https://media-chrome-git-fork-luwes-listbox-fixes-mux.vercel.app/examples/vanilla/control-elements/media-chrome-listbox.html
> Listbox fixes

- src/js/media-container.js
with fallback content. preparation for allowing a slotted poster image in Mux player
related https://github.com/muxinc/media-chrome/issues/380
> fix: make poster slot work with fallback

- src/js/experimental/media-chrome-option.js
Adds new CSS vars for controlling hover and non hover outlines. This fixes an issue where outlines are being cut off on the left and right side of the options.
Hover outline styles are also applied to the `:focus-visible` state for consistency.
There's also a new `--media-option-focus-shadow` var which is helpful for disabling the shadow on `:focus-visible` for simply allowing the option to look the same on hover and focus relying only on the outline vars.
> fix: media-chrome-option outline fix and new css vars

- src/js/experimental/media-chrome-selectmenu.js
Some parts of a hidden listbox are still selectable even though they are hidden, particularly the nested SVG's. This makes them grab focus when moving the cursor or clicking.
> fix: remove pointer events from hidden list boxes

- examples/vanilla/control-elements/media-audio-track-listbox.html
- examples/vanilla/control-elements/media-audio-track-selectmenu.html
- examples/vanilla/control-elements/media-rendition-listbox.html
- examples/vanilla/control-elements/media-rendition-selectmenu.html
- examples/vanilla/index.html
- src/js/constants.js
- src/js/controller.js
- src/js/experimental/index.js
- src/js/experimental/media-audio-track-button.js
- src/js/experimental/media-audio-track-listbox.js
- src/js/experimental/media-audio-track-selectmenu.js
- src/js/experimental/media-chrome-option.js
- src/js/media-container.js
- src/js/media-controller.js
- src/js/utils/utils.js
~todo: fix rendition selection broken after audio track change~
this is a hls.js issue https://github.com/video-dev/hls.js/issues/5749
adds an experimental audio track selectmenu
test url:
- https://media-chrome-git-fork-luwes-audio-tracks-mux.vercel.app/examples/vanilla/control-elements/media-audio-track-selectmenu.html
- https://media-chrome-git-fork-luwes-audio-tracks-mux.vercel.app/examples/vanilla/control-elements/media-audio-track-listbox.html
> feat: add audio track selectmenu

- src/js/constants.js
- src/js/media-container.js
- src/js/media-theme-element.js
This fixes an issue where themes don't render any of the theme template **_on page load_** if the player is smaller than the smallest breakpoint defined. This affects all themes.
The default mux player theme (classic) redefined the `sm` breakpoint as 300 instead of the default which makes it unlikely to appear in normal usage. The new 2023 theme defined a larger `sm` breakpoint and so the UI stopped loading on mobile device sizes.
Although this bug is producible through themes using the breakpoint variables, it's a lower level issue around how and when we decide to render a theme template. This bug exists because when no breakpoints are active, we don't set any new properties on the media controller (like `breakpointsm`), and this in turn means the mutation observer on …
> fix: Themes not rendering if no breakpoint is active on load

- examples/vanilla/control-elements/media-captions-selectmenu.html
- examples/vanilla/control-elements/media-rendition-selectmenu.html
- examples/vanilla/disabled.html
- src/js/experimental/media-chrome-listbox.js
- src/js/experimental/media-chrome-selectmenu.js
- src/js/utils/element-utils.js
- src/js/utils/resize-observer.js
- src/js/utils/server-safe-globals.js
related resize observer performance issue:
https://github.com/WICG/resize-observer/issues/59
test url:
https://media-chrome-git-fork-luwes-selectmenu-overflow-mux.vercel.app/examples/vanilla/control-elements/media-rendition-selectmenu.html
before:
after (w/ scrolling):
> fix: improve selectmenu overflow

- examples/vanilla/control-elements/media-playback-rate-selectmenu.html
- src/js/experimental/media-chrome-listbox.js
- src/js/experimental/media-chrome-option.js
- src/js/experimental/media-chrome-selectmenu.js
- src/js/media-playback-rate-button.js
https://media-chrome-git-fork-luwes-playbackrate-menu-mux.vercel.app/examples/vanilla/control-elements/media-playback-rate-selectmenu.html
> fix: selectmenu anchor right + add listbox row layout

- examples/vanilla/advanced.html
- src/js/controller.js
- src/js/media-chrome-button.js
- src/js/media-chrome-range.js
- src/js/media-container.js
- src/js/media-control-bar.js
- src/js/media-time-display.js
- src/js/media-time-range.js
- src/js/media-volume-range.js
- src/js/themes/youtube.js
- src/js/utils/element-utils.js
- src/js/utils/range-animation.js
related discussion: https://github.com/muxinc/media-chrome/discussions/421
--- 
this change removes the variable `min` and `max` values from the range and sets them to a fixed `0` and `1`.
it simplifies the code as you can see in this PR.
this change doesn't use the UI from input[type=range] anymore but the range is still used as state object, event listener.
this will allow new features and more flexibility, some examples:
- less have to worry about browser inconsistencies in styling the range
- a gradient as background color of the progress bar
- using transitions on the progress bar width and left positioning of the thumb
- it does away with the annoying calculating issue where you have to incorporate the thumb width of the range
> feat: separate slider UI from input range + improve mobile

- src/js/media-chrome-range.js
this improves an issue with calculating the range width and the padding that can be set via CSS vars.
previously if the CSS var was set to `0` or another valid padding value `3px 5px` for example the `calc()` function would fail.
this new approach requires 2 padding elements but it doesn't fail against CSS vars like above
> fix: calc padding CSS var issue

- src/js/media-container.js
> fix: hide cursor on media when controls fade out

- README.md
The current link to the React web-components docs is to the deprecated doc site.
OLD: https://reactjs.org/docs/web-components.html
NEW: https://react.dev/reference/react-dom/components#custom-html-elements
> docs: Fix react web-components link

- src/js/media-container.js
this change fixes an issue where tapping the player on Android would show and hide the controls right away instead of scheduling the hiding after a timeout.
also fixes a small issue where the time range animation would not start right away when the time range became visible,
the animation is disabled when it gets hidden to save CPU.
> fix: Android toggle controls on tapping

- src/js/media-chrome-range.js
> fix: Make backdrop-filter work on Safari with vendor prefix

- docs/src/pages/docs/en/react.md
The Next.js example link was not functional.
> docs: update Next.js demo link in documentation.

- examples/vanilla/media-elements/mux-video.html
- src/js/controller.js
While `defaultsubtitles` and user preference subtitles worked for simple cases, there were various async considerations that were causing issues, including e.g. `autoplay`. This PR updates the logic to be potentially less efficient but more reflective of dev + user preferences and avoids some odd state mismatch possibilities that could result from the prior implementation.
**Example**: Consider cases where the developer has enabled `defaultsubtitles`. Let's say my navigator languages includes English, and my local storage preferred language is Japanese. If the first track asynchronously added is Swedish, none of my subtitle language prefs will match, so I'll pick the Swedish track to show. Then, an English track is added asynchronously. I'll end up here again, and, although the "most …
> fix: default subs async complexities

- examples/vanilla/advanced.html
- examples/vanilla/control-elements/media-settings-menu.html
- src/js/experimental/menu/index.js
- src/js/experimental/menu/media-chrome-dialog.js
- src/js/media-container.js
based on https://github.com/muxinc/media-chrome/pull/788
adds a `media-chrome-dialog` element that could work for the Apple / Netlfix column style menus...
check the last commit for just the element change 
https://github.com/muxinc/media-chrome/pull/795/commits/17c5baa0175a97d6da57bccad33ac8f8e5702423
> feat: add media-chrome-dialog element

- examples/vanilla/advanced.html
- examples/vanilla/control-elements/media-settings-menu.html
- src/js/experimental/menu/media-chrome-menu-item.js
adds a way to hide a menu item based on the size of the submenu items
```css
media-settings-menu-item[aria-haspopup]:is(
:not([submenusize]),
[submenusize="0"],
[submenusize="1"]
) {
display: none;
}
```
> fix: add way to hide menuitems w/ unfilled submenu

- docs/src/components/PageContent/PageContent.astro
- docs/src/layouts/ExamplesLayout.astro
- docs/src/layouts/MainLayout.astro
- docs/src/pages/docs/en/examples/[...example].astro
- examples/vanilla/animated-icons.html
- src/js/media-chrome-range.js
fix #792
https://media-chrome-docs-git-fork-luwes-animated-controls-mux.vercel.app/docs/en/examples/animated-controls
- updates the animated icons / controls example
- adds a `appearance` part to the chrome range for animating that part
- adds the example to the docs examples
> fix: update animated controls

- src/js/utils/element-utils.js
fixes a type error 
```
media-chrome.js?v=705b1957:419 Uncaught TypeError: Cannot read properties of null (reading 'insertRule')
at insertCSSRule (media-chrome.js?v=705b1957:419:40)
at getOrInsertCSSRule (media-chrome.js?v=705b1957:397:10)
at new MediaChromeRange (media-chrome.js?v=705b1957:3418:23)
at new MediaTimeRange (media-chrome.js?v=705b1957:5473:5)
at element (chunk-XL73LIG3.js?v=705b1957:444:19)
at Object.create [as c] (**.svelte:863:99)
at Object.update [as p] (**.svelte:870:42)
at update (chunk-XL73LIG3.js?v=705b1957:1333:32)
at flush (chunk-XL73LIG3.js?v=705b1957:1299:9)
```
> fix: missing sheet typeerror

- src/js/experimental/media-chrome-selectmenu.js
- src/js/media-chrome-range.js
- src/js/media-loading-indicator.js
- src/js/media-text-display.js
- src/js/media-time-display.js
- src/js/utils/element-utils.js
same than the previous bug fix. 
good it uncovered some more issues that are related to trying to access a style sheet before connected to the DOM which seems not possible.
we still keep the dummy CSSStyleRule in the return to not have type errors but I added a warning and a comment to indicate there might be an issue in the code.
> fix: access sheet before connected to DOM

- src/js/media-chrome-range.js
noticed this error in Mux player Next.js example
> fix: cached CSSStyleRule type error in React

- src/js/experimental/menu/media-chrome-menu-item.js
the suffix cc icon in the menu item was too high, not aligned vertically
> fix: cc icon vertical alignment

- docs/src/pages/docs/en/components/media-time-range.mdx
- examples/vanilla/themes/spotify-theme.html
- src/js/experimental/menu/media-settings-menu-item.js
- src/js/experimental/menu/media-settings-menu.js
- src/js/media-time-range.js
- src/js/themes/microvideo.js
- src/js/themes/netflix.js
- src/js/themes/youtube.js
test url: https://media-chrome-docs-git-fork-luwes-range-box-arrow-mux.vercel.app/docs/en/components/media-time-range
> feat: shifting time box elements with arrow

- src/js/media-chrome-range.js
just noticed this bug in Codesandbox. my bad.
> fix: segments.length typerror

- docs/src/pages/docs/en/examples/[...example].astro
- examples/vanilla/themes/tailwind-audio-theme/index.html
test url: https://media-chrome-docs-git-fork-luwes-tailwind-mux.vercel.app/docs/en/examples/tailwind-audio-theme
used a remote static CSS URL for now because Sandpack doesn't seem to support static local assets without bundling them? 
https://github.com/codesandbox/sandpack/discussions/1101
> docs: add Media Chrome + Tailwind CSS example

- README.md
adds some NPM and jsDelivr stats badges and makes the colors just blue, less colliding with the MC logo. looks cleaner.
> docs(readme): add stats badges + fix colors / logo

- README.md
Existing link gives 404 error. Change to the Get Started page instead.
> Fix React docs link in README.md

- src/js/media-time-range.ts
found a bug when the preview thumbnail is sufficiently big, the time display will stay centered and the arrow underneath will stay positioned anchored to the cursor.
this change makes it so the time display will float together with the arrow until it reaches the limit of the bounding box.
> fix: floating time display position

- examples/vanilla/images/spacebar.svg
- examples/vanilla/index.html
- examples/vanilla/tooltips.html
- src/js/index.ts
- src/js/labels/labels.ts
- src/js/media-airplay-button.ts
- src/js/media-audio-track-menu-button.ts
- src/js/media-captions-button.ts
- src/js/media-captions-menu-button.ts
- src/js/media-cast-button.ts
- src/js/media-chrome-button.ts
- src/js/media-fullscreen-button.ts
- src/js/media-live-button.ts
- src/js/media-mute-button.ts
- src/js/media-pip-button.ts
- src/js/media-play-button.ts
- src/js/media-playback-rate-button.ts
- src/js/media-playback-rate-menu-button.ts
- src/js/media-rendition-menu-button.ts
- src/js/media-seek-backward-button.ts
- src/js/media-seek-forward-button.ts
- src/js/media-settings-menu-button.ts
- src/js/media-tooltip.ts
- src/js/utils/utils.ts
Adds a new `media-tooltip` element and includes tooltips by default in anything that extends the `media-chrome-button` class. Tooltips can be placed either `top`, `right`, `bottom`, `left` or `none`.
fix #411
> feat!: Tooltips

- README.md
- docs/src/config.ts
- docs/src/pages/docs/en/audio-player.md
- docs/src/pages/docs/en/components/media-audio-track-menu.mdx
- docs/src/pages/docs/en/components/media-captions-menu.mdx
- docs/src/pages/docs/en/components/media-playback-rate-menu.mdx
- docs/src/pages/docs/en/components/media-settings-menu.mdx
- docs/src/pages/docs/en/get-started.mdx
- docs/src/pages/docs/en/migration/from-3.x-to-4.0.md
- docs/src/pages/docs/en/themes/index.md
https://media-chrome-docs-git-v4-migration-mux.vercel.app/docs/en/migration/from-3.x-to-4.0
> docs: add v4 migration + docs

- docs/src/pages/docs/en/architecture.md
- docs/src/pages/docs/en/keyboard-shortcuts.md
Hi Mux team, I've found some broken URLs after TypeScript migration and tried to address some of them (renaming from js to ts).
Please review, I've updated some lines of code links to match the new code.
Also, I've found that some MDX files have that problem but it's a story for another time.
> docs: change doc urls

- src/js/media-chrome-range.ts
- src/js/media-time-range.ts
- src/js/media-volume-range.ts
> fix: NaN valueAsNumber Safari error

- docs/src/pages/docs/en/components/media-poster-image.mdx
This doc change is inspired by the comment by @luwes here:
https://github.com/muxinc/media-chrome/issues/904#issuecomment-2104699433
PS: Maintainer edits are allowed. Feel free to change the text as you see fit.
> docs: Add a note about img tag in media-poster-image.mdx

- src/js/media-preview-chapter-display.ts
> fix: CJS issue with default & named import

- src/js/menu/media-chrome-menu.ts
- src/js/utils/element-utils.ts
regression in the previous fix. 
Safari!!!!
> fix: Safari (webkit) style tag styles not applied

- src/js/media-chrome-button.ts
> fix: tooltip type error

- src/js/media-chrome-button.ts
fix #991
related https://github.com/muxinc/elements/issues/865
> fix: tooltip causing page overflow

- src/js/media-store/state-mediator.ts
this fixes an issue where the chapters were not being loaded in the UI because the track event was not fired.
> fix: chapters event w/ preload none

- examples/vanilla/mobile.html
- src/js/media-store/state-mediator.ts
related #910
this fixes an issue where when you seek before the video is loaded we don't set the video.currentTime.
it's fine to set the currentTime anytime. it doesn't throw for a valid number value. 
but users have to set the `defaultduration` in some cases. not sure with iOS and native HLS.
> fix: seeking when preload is none

- examples/vanilla/mobile.html
- src/js/media-chrome-range.ts
- src/js/media-time-range.ts
fix #921, fix #983
- Brushed up mobile example https://media-chrome-git-fork-luwes-range-css-parts-mux.vercel.app/examples/vanilla/mobile.html
- Removes the background element, we can use the track element for setting the CSS background.
- Adds CSS parts: `thumb`, `track`, `progress`, `buffered`.
- `--media-range-track-color` CSS var is removed from JS docs, this was left over from the old structure with CSS linear-gradient where it represented the color of the range section on the right of the thumb.
1. a smooth track height transition on hover looks like
```css
media-time-range::part(track) {
transition: transform 0.2s;
transform: scaleY(1);
}
media-time-range:hover::part(track) {
transform: scaleY(1.5);
}
```
2. adding border-radius to track buffered and track progress elements
```css …
```
> feat: add range CSS parts

- docs/src/pages/docs/en/components/media-rendition-menu.mdx
I did not just lose 4 hours of my life trying to find out why the rendition menu wasn't working 🥲 
To prevent someone else from making the same mistake, I added this warning. Copied it from other menu pages that already included this warning, which I only encountered after reverse engineering how the menu works myself 😅 
Hope it's helpful to at least one person out there!
> docs: Added reminder for menu import to rendition menu docs

- src/js/media-chrome-button.ts
In #994 `overflow-x: hidden` was added to the tooltips to prevent unwanted overflows. `hidden` on a single axis does however introduce scrollbars on Windows devices and Mac's who enabled scrollbars to show always (this is great to emulate how a big part of users see your website, which is why I have it enabled). 
Changing the overflow to `overflow-x: clip` will achieve the same result, but won't show a scrollbar. Which is what I added in this PR. See video below showcasing the issue and fix. Let me know your thoughts.
cc @luwes 
Fixes #1000 
https://github.com/user-attachments/assets/67509a11-099f-4b02-ba35-1e0acc46d003
> fix: Use overflow clip in tooltip button to prevent scrollbar

- src/js/media-chrome-button.ts
This fixes an a11y test for media-tooltip not being focusable.
> fix: make tooltip not focusable to fix a11y

- src/js/media-chrome-range.ts
fix #999
I can't reproduce it anymore so hopefully fixed.
the bug happened when `updateSegments` was called multiple times, easier to reproduce with preload none. 
`insertCSSRule` created a rule every time `updateSegments` was called so it possibly happened while the user hovered over a chapter.
> fix: sticky chapter on mouseout

- src/js/utils/platform-tests.ts
> fix: iOS volume support bug

- src/js/media-tooltip.ts
- src/js/utils/element-utils.ts
> fix: tooltip overflow causing scrollbar

- src/js/media-container.ts
As discussed in https://github.com/muxinc/media-chrome/pull/1057.
Apologies, not sure why it's auto-formatting the innerHTML template string, am I missing an extension or something?
To answer a few questions from the other PR:
> valid points though the constructor is called on an upgrade and most of the time that is on connected.
Generally true, but not when the element is created in-memory (`document.createElement` or via template) and not yet attached to the DOM. Quite common practice in modern frameworks (e.g., Vue/Solid/Svelte).
> I believe we put it there because it is just setup once but it could be an oversight. it doesn't cause any serious issues but a new PR putting it in connectedCallback seems good to me. last I checked the cleanup logic is not absolutely required because the …
> fix: remove media container observers on disconnect

- src/js/media-controller.ts
- src/js/media-store/media-store.ts
- src/js/react/media-store.tsx
I'm having the same problem, as the described in [this](https://github.com/muxinc/media-chrome/issues/886) issue.
The error I receive:
```
media-controller.js:440 Uncaught TypeError: (0 , import_media_store.default) is not a function
at MediaController.setupDefaultStore_fn (media-controller.js:440:1)
at MediaController.connectedCallback (media-controller.js:219:1)
```
Which shows me, that the problem is here:
`var import_media_store = __toESM(require("./media-store/media-store.js"), 1);`
By making **createMediaStore** a named export, and using that, this problem disappears, and the video player works perfectly.
> Made createMediaStore a named import

- examples/vanilla/basic-video.html
- src/js/media-container.ts
Related to #874
- Added `--media-control-transition-out` CSS variable to optionally change the transition effect when hiding the `<media-controller>` component.
- Added `--media-control-transition-in` CSS variable to optionally change the transition effect when showing the `<media-controller>` component.
- Added example of use in `basic-video.html`
> feat: add CSS variable to customize the <media-controller> hide transition

- examples/vanilla/control-elements/media-error-dialog.html
- src/js/media-store/state-mediator.ts
- src/js/media-store/util.ts
this change hides the error dialog when playback recovers (playing event fires and media state indicates playing).
> fix: hide error dialog on playback recovery

- docs/src/pages/docs/en/components/media-time-range.mdx
- src/js/media-chrome-range.ts
adds a `thumb` slot for range elements. 
this is required for some CSS features like animations because the declared keyframes have to be in the same scope as the element to which they are applied.
> feat: add range `thumb` slot

- src/js/menu/media-rendition-menu.ts
Resolves #1052
I added conditions to check if the `Auto` option is selected when the menu is rendered and when it detects a change. If `Auto` is selected, the `mediaHeight` will be shown in the option.
https://github.com/user-attachments/assets/2e8513f1-8c16-420d-a60b-94722f79999e
> show Auto(mediaHeight) in rendition menu

- src/js/media-store/request-map.ts
- src/js/media-store/state-mediator.ts
Closes #1072
- `MEDIA_UNMUTE_REQUEST`: When unmuting, if the preferred volume is too low (<= 0.25), set the volume to 0.25. Otherwise, restore the preferred volume.
- `MEDIA_VOLUME_REQUEST`: When volume is 0 and are unmuted, automatically mute.
- `mediaMuted` set behavior: When muting, set `media-chrome-pref-muted` to `true` in localStorage and when unmuting set it to `false`.
- `stateOwnersUpdateHandlers` behavior: calls `mediaMuted`'s set with the `mutedPref` value.
I replicated the same user experience as yt when muting and unmuting (restoring the previously selected volume), with the exception that if the preferred volume is too low (<=0.25), it is set to 0.25 to ensure the audio is clearly perceptible. I'm open to any other suggestions for doing this :)
> feat: persist mute state

- docs/src/pages/docs/en/components/media-controller.md
- examples/nextjs-with-typescript/src/app/globals.css
- src/js/constants.ts
- src/js/extras/media-clip-selector/index.ts
- src/js/media-chrome-button.ts
- src/js/media-chrome-range.ts
- src/js/media-container.ts
- src/js/media-live-button.ts
- src/js/media-time-display.ts
- src/js/menu/media-chrome-menu-item.ts
- src/js/menu/media-chrome-menu.ts
This PR resolves [issue #756](https://github.com/muxinc/media-chrome/issues/756), addressing the case where controls and the cursor should hide even when hovering over the controls.
- Added the alwaysHideControls attribute to the media controller.
- When this attribute is present, controls and the cursor will hide after user inactivity, even if the user is hovering over the controls only if video is playing and not casting.
- After clicking play, if the user does not move the cursor, both the controls and cursor will hide—even when hovering over the controls.
- Controls and cursor will only hide if the user is not hovering over the controls is playing and is not casting
> feat:hide-cursor-controls-on-inactivity

- src/js/media-store/state-mediator.ts
related https://github.com/muxinc/elements/issues/1062
fixes the above issue by delaying toggling subtitles on by default until the video loadstart event is triggered.
> fix: race condition w/ default subtitles (Vue)

- examples/vanilla/basic-i18n.html
- src/js/media-controller.ts
- src/js/utils/i18n.ts
This adds ~~a singleton class~~ `let` to manage the language, and uses the browser language as fallback. If the browser language isn't present as language file, it'll just grab the `en`, like it did before.
The language for this can be set through an attribute on media-controller like in the example. So: 
```html
<media-controller language="fr"></media-controller>
```
Now this can be managed outside media-chrome through a cookie, interface element or whatsoever.
> feat: set i18n through media-controller

- docs/src/config.ts
- docs/src/pages/docs/en/components/media-controller.md
related 
https://github.com/muxinc/media-chrome/pull/1071
https://github.com/muxinc/media-chrome/pull/1105
> docs: add `lang` attribute in media-controller doc

- examples/vanilla/index.html
- middleware.ts
- package-lock.json
- package.json
- vercel.json
We'd like to encourage users to access media chrome through npm or a CDN like jsdeliver
> Discourage external access to example JS

- src/js/utils/i18n.ts
This code assumes that if there is a navigator, that `navigator.language` exists. Ran into issues server rendering on Cloudflare since they don't have this property.
I've made a report on their end, but this should be checked so we can safely fallback to `en` 
https://github.com/cloudflare/workerd/issues/4067
> Check that language exists before splitting

- src/js/media-store/state-mediator.ts
- src/js/utils/server-safe-globals.ts
Fixes #1132 
You can test with this VTT file:
```
WEBVTT
00:00:00.000 --> 00:00:11.000
Intro
00:00:11.000 --> 00:01:11.000
test &amp; test
00:01:11.000 --> 00:02:11.000
test &lt; &gt; &quot; &apos;
00:02:11.000 --> 00:03:11.000
test &copy; &reg; &trade;
```
- `&lt;` should display as <
- `&gt;` should display as >
- `&quot;` should display as "
- `&apos;` should display as '
- `&copy;` should display as ©
- `&reg;` should display as ®
- `&trade;` should display as ™
> fix: decode special characters in chapter text

- package-lock.json
- package.json
fix #1158
shouldn't be part of Media Chrome's dependencies
> fix: move vercel edge to dev dep

- src/js/media-controller.ts
- src/js/media-store/state-mediator.ts
Closes #1194 
This PR prevents storing local storage values in the following cases:
- When the `muted` attribute is present on the media element
- When the `nomutedpref` attribute is present on the media-controller
- When the `novolumepref` attribute is present on the media-controller
- Added `nomutedpref` attribute to the media controller
- Prevent storing muted preference if `muted` or `nomutedpref` are present
- Prevent storing volume preference if `muted` or `novolumepref` are present
> Feat: Prevent storing local storage values if not used

- src/js/media-controller.ts
- test/unit/media-controller.spec.ts
Closes #1169 
Conditionally enable or disable hotkeys based on the presence of the `NO_HOTKEYS` attribute.
> Fix: `nohotkeys` prop disables all shortcuts

- src/js/media-fullscreen-button.ts
- src/js/media-store/request-map.ts
- src/js/media-store/state-mediator.ts
Closes [this issue](https://github.com/muxinc/elements/issues/1169)
- In order to maintain accessibility, when fullscreen is entered by keyboard, the focus will be on the fullscreen button. Pressing the spacebar will enter/exit fullscreen.
- When fullscreen is entered by click, the focus will be on the media element. Pressing the spacebar will play/pause the video (enabling player hotkeys).
> feat: hotkeys are now available after entering fullscreen by click
