gulpfile.js
package-lock.json
package.json
src/js/media-chrome-button.js
src/js/media-chrome-element.js
src/js/media-chrome-menu-button.js
src/js/media-chrome-menu.js
src/js/media-chrome-menuitem.js
src/js/media-chrome-popup.js
src/js/media-chrome-range.js
src/js/media-chrome-submenu-menuitem.js
src/js/media-chrome.js
src/js/media-control-bar.js
src/js/media-current-time-display.js
src/js/media-duration-display.js
src/js/media-forward-button.js
src/js/media-fullscreen-button.js
src/js/media-mute-button.js
src/js/media-pip-button.js
src/js/media-play-button.js
src/js/media-poster.js
src/js/media-progress-range.js
src/js/media-replay-button.js
src/js/media-settings-popup.js
src/js/media-title-element.js
src/js/media-volume-range.js
src/js/utils/defineCustomElement.js
src/js/video-js-element.js

- Moved custom element definition code into utility function
- Updated gulp build script to use ES6 modules to match the `package.json` configuration.

defineCustomElement

---

examples/demo.html
src/js/media-chrome-button.js
src/js/media-chrome.js
src/js/media-playback-rate-button.js

Added playback rate/speed control

---

examples/container-less.html
examples/youtube-theme.html
src/js/media-chrome-button.js
src/js/media-chrome-range.js
src/js/media-chrome.js

* Revealing of the volume range on hover/focus
* Focus styles only when navigating with the keyboard

Youtube-style theme

---

examples/container-less.html
src/js/media-chrome-html-element.js
src/js/media-fullscreen-button.js
src/js/media-pip-button.js
src/js/utils/dashedToCamel.js

Also includes an additional fix for fullscreen elements inside a shadow dom.
Need to do the same for PIP.

Adding attr to fullscreen button to set fs element

---

src/js/media-chrome-container.js
src/js/media-chrome-html-element.js
src/js/media-play-button.js
src/js/media-progress-range.js
src/js/utils/propagateMedia.js

Can now add and remove controls or media elements and
the media property will be set accordingly across controls.

Updated media-chrome to support add/remove els

---

src/js/media-chrome-range.js

https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties for reference

fix/css-var-syntax: fixing nested vars syntax in media-chrome-range.

---

README.md

"where there is a Mux url, give it a UTM" - Athena, probably

Appease the attribution gods

---

package.json
yarn.lock

Add missing `np` dev dependency NPM package needed for publishing.

Add np dev dependency

---

docs/media-controller.md

Add small fixes to https://github.com/muxinc/media-chrome/blob/main/docs/media-controller.md

Add small fixes to docs

---

src/js/media-controller.js

Ran into a type error today that happens when media is removed. Is this old code maybe?

Fix type error in unset callback

---

README.md

Wasn't really sure where to put it. Feel free to make suggestions

Add the examples link to readme again

---

docs/media-seek-forward-button.md

Fix small typo in forward button doc.

Fix forward btn doc

---

snowpack.dev.config.cjs
src/js/media-controller.js

fixes #140
Also updated media controller APIs to include needed functions and centralized logic.

Fixed mute button default state

---

examples/control-elements/media-playback-rate-button.html
examples/index.html

Depends on #129, but I can rebase this when that one is merged. 0550168cc5b0f3f0d300e1ed0e6ce4894f3fc31e is the main change here.

 docs(playback-rate-button): add example page for playback rate button 

---

src/js/media-controller.js

Fixes a bug that gets thrown when setting attributes in the custom element constructor.
See https://stackoverflow.com/questions/54857905/deferred-setattribute-call-in-custom-element-constructor-causes-dom-error-is-it

Fix custom element constructor attribute bug

---

docs/styling.md
examples/control-elements/media-time-range.html
src/js/constants.js
src/js/media-controller.js
src/js/media-time-range.js

Hook up media-buffered attribute to progress background

---

examples/media-elements/wistia.html

Related to https://github.com/muxinc/media-chrome/issues/197
Fixes an issue with volume and duration state on player load.

Upgrade Wistia video element

---

demos/nextjs-with-typescript/styles/globals.css
docs/styling.md
examples/advanced.html
examples/media-elements/jwplayer.html
examples/media-elements/wistia.html
examples/state-change-events-demo.html
src/js/media-control-bar.js
src/js/media-loading-indicator.js

Removes the need for styling it specifically most of the times.
In the control-bar change it to 44px default.

Change default loading indicator width 100px

---

examples/advanced.html
examples/basic.html
src/js/media-container.js

Should be merged via a squash merge, probably.

fix: conslidate and simplfy selectors dealing with pointer-events

---

package.json
yarn.lock

just adds eslint so it can be merged separate from https://github.com/muxinc/media-chrome/pull/255

test: add eslint

---

scripts/esbuild.js

chore: make yarn dev auto get free port

---

src/js/media-captions-button.js
src/js/media-cast-button.js
src/js/media-fullscreen-button.js
src/js/media-loading-indicator.js
src/js/media-mute-button.js
src/js/media-pip-button.js
src/js/media-play-button.js

fix: style override from Tailwind CSS 

---

examples/index.html
examples/media-elements/media-playlist.html

[Updated media-playlist](https://github.com/muxinc/media-playlist/pull/1) based on [the playlist discussion](https://github.com/muxinc/media-chrome/discussions/97). Adding an example to media-chrome.

Add media playlist example

---

docs/src/pages/en/media-mute-button.md

This section is about the mute button but the example said fullscreen.

[Docs] Update media component in example

---

examples/disabled.html
src/js/media-chrome-button.js
src/js/media-chrome-range.js
src/js/media-seek-backward-button.js
src/js/media-seek-forward-button.js
src/js/media-time-display.js
src/js/media-time-range.js

The final piece I believe is to turn off thumbnails of the time-range when it's disabled. But wanted to get some 👀 to make sure that this direction is fine before making that change.
Another thing that I haven't been able to figure out is if I set up the following css:
```css
[disabled] {
cursor: not-allowed;
}
```
When hovering over the `input` element itself, it would still show the hand cursor. Though, it will not do anything. I tried even adding a part on it and added `[disabled]::part(range)` to the selector above, and it still shows the hand cursor.

feat: support being able to disable buttons

---

src/js/extras/media-clip-selector/index.js
src/js/media-chrome-button.js
src/js/media-controller.js

When creating https://github.com/muxinc/media-chrome/pull/330, it pointed out a few issues that should be fixed. Since I figured #330 might take might be a bit before getting merged, I'd create a separate PR for the specific fixes that should go in.

fix: a couple of fixes

---

src/js/media-chrome-button.js
src/js/media-time-display.js

fix: don't set attributes in a constructor

---

package.json

this was my bad on adding this while it's not absolutely needed when using a CDN that bundles automatically. shouldn't worry about it

feat: remove esm-module

---

README.md

it's actually a little noisy. useful info but maybe needs to be placed somewhere else?

docs: add version, size badge

---

src/js/media-theme-element.js
src/js/utils/template-processor.js

This fixes an issue where the inner template aliases were not transformed and broke the directives.

Fix directive aliases in inner template

---

src/js/media-theme-element.js
src/js/utils/template-parts.js
src/js/utils/template-processor.js

player tests were failing because it tried to evaluate inner templates as regular expressions

fix: inner template bug

---

src/js/utils/template-parts.js

Adds most types for the template parts utilities.
One difficult one is the `element` argument of the `parse()` function. 
If you feel the calling please go ahead, I couldn't figure it out right away.

Template Parts types

---

.github/workflows/cd.yml
.github/workflows/ci.yml
src/js/extras/media-clip-selector/index.js
src/js/index.js
src/js/media-airplay-button.js
src/js/media-captions-button.js
src/js/media-captions-listbox.js
src/js/media-cast-button.js
src/js/media-chrome-button.js
src/js/media-chrome-listbox.js
src/js/media-chrome-listitem.js
src/js/media-container.js
src/js/media-controller.js
src/js/media-fullscreen-button.js
src/js/media-gesture-receiver.js
src/js/media-mute-button.js
src/js/media-pip-button.js
src/js/media-play-button.js
src/js/media-playback-rate-button.js
src/js/themes/media-theme-demuxed-2022.js

was accidentally included in the main Media Chrome bundle

fix: remove Demuxed theme 2022 from MC bundle

---

src/js/media-time-range.js

fix: no need for rounding anymore, step=any

---

test/web-test-runner.config.js

test: remove noisy lit in dev mode warning

---

README.md
docs/src/pages/en/audio-player.md
examples/media-elements/dash.html
examples/media-elements/hls.html
examples/media-elements/media-playlist.html
examples/media-elements/youtube.html
examples/themes/youtube-theme.html

Also added more specific versions for a few projects where needed.

doc: Manual readme version bump to 0.17

---

examples/control-elements/media-captions-listbox.html
examples/control-elements/media-chrome-listbox.html
examples/control-elements/media-chrome-menu-button.html
src/js/media-captions-listbox.js
src/js/media-captions-menu-button.js
src/js/media-chrome-listbox.js
src/js/media-chrome-listitem.js
src/js/media-chrome-menu-button.js

Implementing some of https://github.com/muxinc/media-chrome/issues/387

Listbox followups

---

.github/CONTRIBUTING.md

Modeled after https://github.com/muxinc/elements/blob/main/CONTRIBUTING.md

docs: add base CONTRIBUTING.md

---

src/js/media-current-time-display.js
src/js/media-duration-display.js
src/js/media-time-display.js

Fixes issue https://github.com/muxinc/media-chrome/issues/88

fix: adds a 0:00 default time, fixes #88

---

examples/experimental/themes/youtube-theme.html
examples/media-elements/youtube.html
examples/themes/youtube-theme.html

related https://github.com/muxinc/youtube-video-element/pull/19 
fixes #280

chore: upgrade `youtube-video-element` to v0.1.0

---

src/js/media-theme-element.js
src/js/utils/template-processor.js

this adds the breakpoint attributes to the template params that this should work:
```html
<template if="breakpointSm">
<template if="breakpointMd == null">....
```

feat: add audio, targetLiveWindow and breakpointX template params

---

docs/src/pages/en/react.md

docs: fix NextJS demo link

---

examples/media-elements/jwplayer.html
examples/media-elements/videojs.html
examples/media-elements/vimeo.html
examples/media-elements/wistia.html

made some updates to how these modules import.
they are now build-less ESM modules.

chore: fix custom media el imports

---

docs/src/pages/en/styling.md

docs: add missing --media-range-bar-color

---

docs/src/components/HeadCommon.astro

chore: add fathom script

---

.github/workflows/ci.yml

adds the Codecov GH action to see test coverage in PR's

chore: add codecov action

---

src/js/media-container.js
src/js/media-controller.js

this event was firing constantly when mouse hovering the media chrome.

fix: over firing user-inactive event, attr name

---

src/js/labels/labels.js
src/js/media-live-button.js
src/js/themes/microvideo.js
src/js/themes/minimal.js
test/unit/media-controller.spec.js

- adds aria-disabled="true" to media-live-button when it's playing live
- adds aria-label's based on live status

fix: inactive live button

---

docs/src/pages/en/components/media-live-button.md
docs/src/pages/en/styling.md
examples/vanilla/components.html
examples/vanilla/index.html
src/js/media-live-button.js
src/js/media-poster-image.js
src/js/media-text-display.js
src/js/media-time-display.js
src/js/media-time-range.js
src/js/themes/microvideo.js
src/js/themes/minimal.js
src/js/themes/netflix.js
src/js/themes/youtube.js

BREAKING CHANGE: Change `--media-live-indicator-color` to `--media-live-button-indicator-color`, `--media-time-buffered-color` to `--media-time-range-buffered-color`, `--media-background-position` to `--media-poster-image-background-position`, and `--media-background-size` to `--media-poster-image-background-size`.

fix: css variables consistency updates

---

src/js/constants.js
src/js/media-container.js

This dispatches a CustomEvent each time the breakpoints list on media-controller _actually_ changes.

feat: Adding custom event for breakingpoint changing

---

src/js/media-seek-backward-button.js
src/js/media-seek-forward-button.js
src/js/media-time-display.js
src/js/utils/seek.js

Additional props and types for existing attributes and some small bits of clean up. I moved the duplicated utils into a separate file to make them easier to maintain and test in the future.

feat: Add props and types to seek forwards and backwards elements

---

docs/src/components/Sandpack.jsx
docs/src/components/SandpackContainer.astro
docs/src/config.ts
docs/src/layouts/MainLayout.astro
docs/src/layouts/MediaElementLayout.astro
docs/src/pages/en/components/media-time-range.mdx
docs/src/pages/en/media-elements/cloudflare-video.mdx
docs/src/pages/en/media-elements/dash-video.mdx
docs/src/pages/en/media-elements/hls-video.mdx
docs/src/pages/en/media-elements/jwplayer-video.mdx
docs/src/pages/en/media-elements/mux-video.mdx
docs/src/pages/en/media-elements/shaka-video.mdx
docs/src/pages/en/media-elements/spotify-audio.mdx
docs/src/pages/en/media-elements/videojs-video.mdx
docs/src/pages/en/media-elements/vimeo-video.mdx
docs/src/pages/en/media-elements/wistia-video.mdx
docs/src/pages/en/media-elements/youtube-video.mdx
src/js/media-controller.js

https://media-chrome-docs-git-fork-luwes-media-elements-mux.vercel.app/en/media-elements/hls-video

docs: add media element pages

---

docs/src/components/SandpackContainer.astro
docs/src/styles/index.css

- fixes the open Sandbox link FOUC'ing for a sec
- fixes the code editor jumping down for stacked Sandpack's

docs: fix Sandpack glitches

---

src/js/media-time-range.js
src/js/media-volume-range.js

Adds missing props. Fixes attr documentation for mediapreviewtime in Time Range.

feat: Media Time Range and Volume Range props

---

src/js/media-live-button.js
src/js/media-loading-indicator.js
src/js/media-mute-button.js

Add missing props for Live Button, Loading Indicator, and Mute button components.

feat: Live Button and Mute button props

---

docs/src/config.ts

New advanced section, remove Media States section.

docs: advanced section in sidebar

---

src/js/controller.js
src/js/utils/fullscreen-api.js
src/js/utils/platform-tests.js

fix: iOS fullscreen state bug

---

docs/src/config.ts
docs/src/pages/en/migration/from-0.x-to-1.0.md
src/js/media-theme-element.js
src/js/themes/demuxed-2022.js

Demo docs page: https://media-chrome-docs-git-fork-cjpillsbury-docs-0x-1x-mi-d37eb4-mux.vercel.app/en/migration/from-0.x-to-1.0

Docs/0.x 1.x migration guide

---

src/js/controller.js

fix: fullscreen state getter w/o event

---

README.md

test url: https://github.com/muxinc/media-chrome/blob/be5cf32a49d909348abfa7f19ac8d6483cb1d2db/README.md

docs: add new Media Chrome logo

---

src/js/media-captions-button.js
src/js/media-cast-button.js
src/js/media-chrome-range.js
src/js/media-fullscreen-button.js
src/js/media-gesture-receiver.js
src/js/media-live-button.js
src/js/media-pip-button.js
src/js/media-play-button.js
src/js/media-poster-image.js
src/js/media-preview-thumbnail.js
src/js/media-time-range.js
src/js/themes/netflix.js
src/js/themes/winamp.js
src/js/themes/youtube.js

related issue https://github.com/muxinc/media-chrome/discussions/646

feat: add `backdrop-filter` to range track & bg

---

docs/src/layouts/ComponentLayout.astro
docs/src/layouts/LandingLayout.astro
docs/src/layouts/MainLayout.astro
docs/src/layouts/MediaElementLayout.astro
docs/src/pages/docs/en/audio-player.md
docs/src/pages/docs/en/get-started.mdx
docs/src/pages/docs/en/keyboard-shortcuts.md
docs/src/pages/docs/en/media-element.mdx
docs/src/pages/docs/en/prevent-layout-shift.md
docs/src/pages/docs/en/react.md
docs/src/pages/docs/en/reference/styling.astro
docs/src/pages/docs/en/styling.mdx

docs: improve docs based on feedback

---

package.json
yarn.lock

Fixed by https://github.com/open-wc/custom-elements-manifest/pull/216

chore: fix custom elements manifest & docreference

---

src/js/media-seek-backward-button.js
src/js/media-seek-forward-button.js

fixes #691
Call the attr setting in connectedCallback rather than constructor.

fix: Attr setting error in seek buttons

---

examples/vanilla/standalone-controls.html

test url: https://media-chrome-git-fork-luwes-standalone-controls-mux.vercel.app/examples/vanilla/standalone-controls.html

chore: add live, airplay, cast button

---

docs/src/pages/docs/en/components/media-captions-selectmenu.md
docs/src/pages/docs/en/components/media-playback-rate-selectmenu.md
examples/vanilla/components.html
examples/vanilla/control-elements/media-captions-listbox.html
examples/vanilla/control-elements/media-captions-selectmenu.html
examples/vanilla/control-elements/media-chrome-listbox.html
examples/vanilla/control-elements/media-rendition-listbox.html
examples/vanilla/control-elements/media-rendition-selectmenu.html
examples/vanilla/index.html
src/js/constants.js
src/js/controller.js
src/js/experimental/media-captions-listbox.js
src/js/experimental/media-captions-selectmenu.js
src/js/experimental/media-chrome-listbox.js
src/js/experimental/media-chrome-listitem.js
src/js/experimental/media-chrome-option.js
src/js/experimental/media-playback-rate-listbox.js
src/js/experimental/media-playback-rate-selectmenu.js
src/js/experimental/media-rendition-button.js
src/js/experimental/media-rendition-listbox.js
src/js/experimental/media-rendition-selectmenu.js
src/js/media-container.js
src/js/media-controller.js
src/js/utils/utils.js
test/unit/media-controller.spec.js

Related #387
test urls: 
- https://media-chrome-git-fork-luwes-rendition-select-mux.vercel.app/examples/vanilla/control-elements/media-rendition-listbox.html
- https://media-chrome-git-fork-luwes-rendition-select-mux.vercel.app/examples/vanilla/control-elements/media-rendition-selectmenu.html

Rendition select

---

src/js/media-container.js

fix: set breakpoints on connected 

---

src/js/experimental/media-captions-listbox.js
src/js/experimental/media-chrome-listbox.js
src/js/experimental/media-chrome-option.js
src/js/experimental/media-chrome-selectmenu.js
src/js/experimental/media-rendition-listbox.js

- fixes the media controller id link in shadow dom
- fixes some css vars docs

fix: selectmenu / listbox fixes

---

examples/vanilla/control-elements/media-playback-rate-selectmenu.html

https://media-chrome-git-fork-luwes-custom-select-icon-mux.vercel.app/examples/vanilla/control-elements/media-playback-rate-selectmenu.html

example: add custom select icon w/ selectmenu

---

scripts/react/build.js

fix: account for single child in react wrapper templating.

---

examples/vanilla/themes/demuxed-2022-theme.html
src/js/themes/demuxed-2022.js

test URL: https://media-chrome-git-fork-luwes-demuxed-theme-mux.vercel.app/examples/vanilla/themes/demuxed-2022-theme.html

examples: brush up Demuxed theme 2022

---

.github/workflows/ci.yml
src/js/media-chrome-range.js
src/js/media-time-range.js
src/js/utils/element-utils.js
test/unit/media-captions-listbox.spec.js
test/unit/media-captions-selectmenu.spec.js
test/unit/utils/element-utils.spec.js

fix: time range bug fixes

---

src/js/controller.js
src/js/utils/element-utils.js

fix: fullscreen attr if node is not isConnected

---

src/js/media-container.js

related https://github.com/muxinc/elements/issues/849

fix: prevent unset callback if there is no media

---

docs/astro.config.js
docs/package.json
docs/src/layouts/LandingLayout.astro
docs/src/layouts/MainLayout.astro
docs/yarn.lock

Using the steps here for the static output worked out
https://docs.astro.build/en/guides/integrations-guide/vercel/#choosing-a-target
---
~I think this should work, but I can't run the site locally because of an error I don't understand.~

website: Add vercel analytics

---

examples/vanilla/advanced.html
src/js/experimental/menu/media-audio-track-menu-button.js
src/js/experimental/menu/media-chrome-menu-item.js
src/js/experimental/menu/media-chrome-menu.js
src/js/experimental/menu/media-rendition-menu-button.js
src/js/experimental/menu/media-settings-menu-button.js
src/js/experimental/menu/media-settings-menu.js
src/js/labels/labels.js

fix: add menu button aria labels

---

docs/src/layouts/MainLayout.astro

fix: mobile docs nav

---

src/js/controller.js

Fixes https://github.com/muxinc/media-chrome/issues/809

fix: Safari disableRemotePlayback errors

---

src/js/experimental/menu/media-chrome-menu-item.js

fix: clicking settings menu items with children

---

.github/workflows/cd.yml
.github/workflows/ci.yml
package.json
src/js/media-container.js
src/js/media-controller.js
yarn.lock

fixes https://github.com/epicweb-dev/kcdshop/issues/189
the async logic in handleMediaUpdated was causing rootNode to be undefined when trying to add event listeners.
this bug was only apparent when rapidly connecting / disconnecting media like in many modern JS frameworks

fix(fullscreen): handleMediaUpdated / rootNode race condition

---

examples/vanilla/advanced.html
examples/vanilla/media-elements/hls.html
examples/vanilla/media-elements/media-playlist.html
src/js/controller.js
test/unit/media-rendition-listbox.spec.js
test/unit/media-rendition-selectmenu.spec.js

- fix #820
- fix another bug where the chapter segments were not always rendered

fix: safari InvalidStateError remote playback API error

---

src/js/media-container.js

fix: poster slot fade after play before playing

---

src/js/media-chrome-range.js
src/js/media-preview-chapter-display.js
src/js/media-store/request-map.js
src/js/media-time-range.js

https://media-chrome-git-fork-luwes-chapter-preview-fix-mux.vercel.app/examples/vanilla/advanced.html

fix: chapter preview fine tuning

---

src/js/media-time-range.js
src/js/utils/range-animation.js

fix: account for some dynamic changes to media-time-range

---

examples/vanilla/index.html
examples/vanilla/themes/tailwind-audio-theme/index.html
examples/vanilla/themes/tailwind-audio-theme/input.css
examples/vanilla/themes/tailwind-audio-theme/output.css
examples/vanilla/themes/tailwind-audio-theme/package-lock.json
examples/vanilla/themes/tailwind-audio-theme/package.json
examples/vanilla/themes/tailwind-audio-theme/tailwind.config.js

https://media-chrome-git-fork-luwes-tailwind-audio-theme-mux.vercel.app/examples/vanilla/themes/tailwind-audio-theme/

example: add tailwind css audio theme

---

src/js/media-store/state-mediator.js

fix: cancelWatchAvailability promise catch

---

docs/astro.config.js
docs/package.json
docs/public/robots.txt
docs/src/components/HeadCommon.astro
docs/src/config.ts
docs/yarn.lock

docs: add robots.txt, sitemap-index.xml

---

README.md
docs/src/pages/docs/en/audio-player.md
docs/src/pages/docs/en/get-started.mdx

docs: update MC version to v3

---

docs/src/pages/docs/en/design-principles.md
docs/src/pages/docs/en/development-principles.md

Adding a section for development principles based on a conversation in office hours about a desire to speed up development decision making in a similar way that design principles have.

Adding dev principles; cleaning design principles

---

scripts/react/build.js

adds the missing standalone export for React

fix: add media-chrome/react/media-theme

---

examples/vanilla/themes/demuxed-2022-theme.html
examples/vanilla/themes/microvideo-theme.html
examples/vanilla/themes/minimal-theme.html
examples/vanilla/themes/netflix-theme.html
examples/vanilla/themes/responsive-theme.html
examples/vanilla/themes/youtube-theme.html
src/js/media-theme-element.ts

related https://github.com/muxinc/player.style/issues/39

fix: theme render flicker (breakpoints)

---

examples/vanilla/control-elements/media-captions-menu.html
src/js/media-control-bar.ts
src/js/menu/media-chrome-menu.ts

fix: position menu absolute in control bar

---

src/js/constants.ts
src/js/media-container.ts
src/js/media-store/state-mediator.ts
src/js/menu/media-chrome-menu-item.ts
src/js/menu/media-rendition-menu-button.ts
src/js/menu/media-rendition-menu.ts
src/js/menu/media-settings-menu.ts

fix #877
https://media-chrome-git-fork-luwes-show-auto-quality-mux.vercel.app/examples/vanilla/advanced.html

fix: show current playing quality in settings

---

src/js/media-store/request-map.ts

related https://github.com/muxinc/elements/issues/980

fix: seek to live action

---

src/js/media-theme-element.ts
src/js/menu/media-chrome-menu.ts

fix #980
fix https://github.com/muxinc/player.style/issues/95

fix: menu Safari bug and top overflow bug

---

scripts/react/build.js

this was being converted to an attribute and had no effect 😅

fix: suppressHydrationWarning bug

---

src/js/media-chrome-button.ts

options like transition delay, backdrop-filter, etc...

fix: add button tooltip part for more styling

---

src/js/media-container.ts

setBreakpoints is called in 2 places now so this block should live in that function

fix: move breakpointsComputed set to better place

---

examples/vanilla/advanced.html
examples/vanilla/control-elements/media-error-dialog.html
src/js/media-chrome-dialog.ts

related https://github.com/muxinc/elements/pull/1075
I tried using `@starting-style {}` but couldn't get that to work so let's do it old school.

fix: dialog accessibility hidden, page load bug

---

scripts/react/build.js

Solves [This Issue](https://github.com/muxinc/media-chrome/issues/1083)
- Add ".d.ts" definitions for react components and menu react components

fix: 4.6.0+ no longer has typings for React

---

scripts/cem-plugin-css-vars.js
scripts/react/build.js
src/js/media-theme.ts

related https://github.com/muxinc/media-chrome/pull/1068
there was an issue with naming that showed up in player.style 
https://github.com/muxinc/player.style/pull/166

fix: MediaTheme React type

---

examples/vanilla/media-elements/jwplayer.html

Fixes #1092
- Changed video source
- Updated thumbnails

example: Changed video source of the JW player media example

---

examples/vanilla/media-elements/dash.html

Fixes #1091 
- Changed `dash-video-element` to latest version
- Added esm modifier

example: Changed dash-video-element to latest version and added esm modifier

---

src/js/media-chrome-range.ts
src/js/utils/element-utils.ts

Fixes #883 
Modified the pointer position calculation in `getPointerRatio`

fix: timerange thumb and tooltip drift mobile

---

package-lock.json
package.json
src/js/media-controller.ts
test/unit/resolve-package-exports.spec.ts
test/web-test-runner.config.js

we were seeing some strange behavior with resolving of paths of the `/lang/x.js` path.
did a quick spike on this, simplified our exports object and added some tests

fix: simplify exports, resolve tests. fix lang prop type issue

---

docs/src/pages/docs/en/media-elements/jwplayer-video.mdx

Docs: Updated JWplayer docs video source

---

examples/nextjs-with-typescript/src/app/react-wrappers/player.tsx
scripts/react/build.js
src/js/media-playback-rate-button.ts
src/js/menu/media-playback-rate-menu-button.ts
src/js/menu/media-playback-rate-menu.ts
test/unit/media-playback-rate-button.spec.ts

fix: React rates array

---

.github/workflows/claude.yml

Adding the [Claude Code action](https://github.com/anthropics/claude-code-action) so we can try it out.

add some claude

---

src/js/menu/media-rendition-menu.ts

This PR adds support for multiple bitrates in the rendition menu by:
1. Showing the bitrate when there are multiple renditions with the same height.
2. Sorting renditions based on both height and bitrate (if any have the same height).
---
The way we track the current rendition needs to be revised to support auto and still knowing accurately which rendition is selected. They're conflated under `mediaRenditionSelected` which can only be `auto` or a rendition. 
<details>
<summary>Settings menu item without bitrate</summary>
</details>
<details>
<summary>Settings menu item with bitrate</summary>
</details>
<details>
<summary>Rendition menu with bitrates</summary>
</details>

feat: support multiple bitrates in rendition menu
